<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <PackageTags>csv;fixed-width;text-files;file-parser;import;export</PackageTags>
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
      <Title>Zonkey Text Processing</Title>
      <Authors>Kelly Birr</Authors>
      <Description>Zonkey ORM Library to Text Files</Description>
      <PackageProjectUrl>https://github.com/kellybirr/zonkey</PackageProjectUrl>
      <RepositoryUrl>https://github.com/kellybirr/zonkey</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>


</Project>
