using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.Data.Sqlite;
using Xunit;
using Zonkey.Scaffold;

namespace Zonkey.Scaffold.Tests.Golden;

// Program.Main's "generate" path reports through the default writer, which is Console.Out when
// invoked the way CliSmokeTests and this class invoke it (no DI override) — so this class joins
// the same "ScaffoldConsole" collection for the same reason CliSmokeTests does. See the doc
// comment on ScaffoldConsoleCollection in Cli/CommandTests.cs.
[Collection("ScaffoldConsole")]
public class ZooGoldenTests : IAsyncLifetime
{
    private string _dir = "";
    private string _dbPath = "";
    private string _conn = "";
    private string _entitiesDir = "";
    private string _nullableEntitiesDir = "";
    private string _fieldEntitiesDir = "";

    public async ValueTask InitializeAsync()
    {
        _dir = Directory.CreateTempSubdirectory("zgolden").FullName;
        _dbPath = Path.Combine(_dir, "zoo.db");
        _conn = $"Data Source={_dbPath}";
        _entitiesDir = Path.Combine(_dir, "Entities");
        _nullableEntitiesDir = Path.Combine(_dir, "EntitiesNullable");
        _fieldEntitiesDir = Path.Combine(_dir, "EntitiesField");

        await using (var cnxn = new SqliteConnection(_conn))
        {
            await cnxn.OpenAsync();
            await using var cmd = cnxn.CreateCommand();
            cmd.CommandText = File.ReadAllText(
                Path.Combine(AppContext.BaseDirectory, "Golden", "zoo-sqlite.sql"));
            await cmd.ExecuteNonQueryAsync();
        }

        int exit = await Program.Main([
            "generate",
            "--provider", "sqlite",
            "--connection", _conn,
            "--namespace", "Zoo.Data",
            "--out", _entitiesDir,
            "--wrapper-class", "ZooDatabase",
            "--field-keyword", "false",
            "--config-file", Path.Combine(_dir, "none.json")
        ]);

        Assert.Equal(0, exit);

        // Second generation pass, explicitly with --nullable-refs true. The temp directory this
        // test generates into has no .csproj, so ProjectProbe finds nothing and Emit:NullableRefs
        // resolves to "auto" -> false — the default run above never emits "#nullable enable" or a
        // single "string?". Passing --nullable-refs true bypasses ProjectProbe's detection
        // entirely, which is required to exercise the CS8669 guard described on
        // CSharpEntityEmitter.Emit: a file starting with "// <auto-generated>" disables the
        // compiler's nullable annotation context, so "#nullable enable" must be emitted whenever
        // the type mapper bakes a "?" into a ClrType, or every nullable reference property raises
        // CS8669 under TreatWarningsAsErrors.
        int nullableExit = await Program.Main([
            "generate",
            "--provider", "sqlite",
            "--connection", _conn,
            "--namespace", "Zoo.Data",
            "--out", _nullableEntitiesDir,
            "--wrapper-class", "ZooDatabase",
            "--field-keyword", "false",
            "--nullable-refs", "true",
            "--config-file", Path.Combine(_dir, "none.json")
        ]);

        Assert.Equal(0, nullableExit);

        // Third pass: the shape a modern consumer actually gets. ProjectProbe selects the `field`
        // keyword automatically for a net10.0 project and nullable refs automatically for
        // <Nullable>enable</Nullable>, so `field` + nullable together is the default emit shape
        // for any project created since .NET 10 — and it was the one combination with no compile
        // coverage at all. Both are forced explicitly here because the temp output directory has
        // no .csproj for ProjectProbe to read.
        int fieldExit = await Program.Main([
            "generate",
            "--provider", "sqlite",
            "--connection", _conn,
            "--namespace", "Zoo.Data",
            "--out", _fieldEntitiesDir,
            "--wrapper-class", "ZooDatabase",
            "--field-keyword", "true",
            "--nullable-refs", "true",
            "--config-file", Path.Combine(_dir, "none.json")
        ]);

        Assert.Equal(0, fieldExit);

        // Pool eviction happens on Dispose, but SQLite keeps the file mapped until pools are
        // cleared explicitly; do it once up front so a later test in this class can safely
        // reopen the same file without file-lock contention on Windows.
        SqliteConnection.ClearAllPools();
    }

    public ValueTask DisposeAsync()
    {
        SqliteConnection.ClearAllPools();
        Directory.Delete(_dir, recursive: true);
        return ValueTask.CompletedTask;
    }

    // ---- Layer 1: golden text -------------------------------------------------
    //
    // Catches drift in the generator's text output and makes intentional changes reviewable as
    // diffs. This layer cannot catch a scaffolder that emits code which fails to compile, or
    // code that compiles but maps the wrong DbType/IsAutoIncrement — that is what layers 2 and 3
    // are for.

    [Theory]
    [InlineData("Species")]
    [InlineData("Animal")]
    [InlineData("Exhibit")]
    [InlineData("Zookeeper")]
    [InlineData("FeedingSchedule")]
    public void Generated_text_matches_the_golden_file(string className)
    {
        string actual = File.ReadAllText(Path.Combine(_entitiesDir, $"{className}.g.cs"))
            .ReplaceLineEndings("\n");
        string expectedPath = Path.Combine(
            AppContext.BaseDirectory, "Golden", "Expected", $"{className}.g.cs.txt");

        // To refresh after an intentional generator change:
        //   copy the generated file over the .txt and review the diff by hand before accepting.
        string expected = File.ReadAllText(expectedPath).ReplaceLineEndings("\n");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void Species_survives_singularization()
        => Assert.True(File.Exists(Path.Combine(_entitiesDir, "Species.g.cs")));

    [Fact]
    public void Composite_key_marks_every_key_column()
    {
        string code = File.ReadAllText(Path.Combine(_entitiesDir, "FeedingSchedule.g.cs"));
        Assert.Equal(3, code.Split("IsKeyField = true").Length - 1);
    }

    // ---- Layer 2: it compiles -------------------------------------------------
    //
    // The classic scaffolder failure: text that looks plausible but does not compile (bad using,
    // mismatched type, syntax error introduced by a template edit). A text diff cannot catch
    // this; only actually compiling the emitted source against the real Zonkey.Data assembly can.

    /// <summary>
    /// The default emit shape (<c>--nullable-refs false</c>) — what a
    /// <c>&lt;Nullable&gt;disable&lt;/Nullable&gt;</c> or net48 consumer actually gets. Held to
    /// the same warnings-as-errors bar as the nullable, `field` and keyword passes: the guarantee
    /// this suite states is "generated code builds clean", and asserting it on only half the
    /// emit matrix is how the last gap survived.
    /// </summary>
    [Fact]
    public void Generated_code_compiles_against_Zonkey_Data()
    {
        CompilationResult result = Compile(
            "GeneratedZoo", NullableContextOptions.Enable, _entitiesDir, warningsAsErrors: true);

        Assert.True(result.Success, "Generated code did not compile:\n" + result.Errors);
    }

    // ---- Layer 3: it round-trips ----------------------------------------------
    //
    // The only layer that proves the *mapping* is right, not just the text. A wrong DbType or a
    // missed IsAutoIncrement compiles cleanly and passes layer 2, then fails here because the
    // insert either throws or the identity value never comes back.

    [Fact]
    public async Task Generated_classes_round_trip_against_the_database()
    {
        CompilationResult compiled = Compile(
            "GeneratedZooRuntime", NullableContextOptions.Disable, _entitiesDir,
            warningsAsErrors: true);
        Assert.True(compiled.Success, "Generated code did not compile:\n" + compiled.Errors);
        Assembly assembly = compiled.Load();

        Type speciesType = assembly.GetType("Zoo.Data.Species")
            ?? throw new InvalidOperationException("Species type missing.");

        await using var cnxn = new SqliteConnection(_conn);
        await cnxn.OpenAsync(TestContext.Current.CancellationToken);

        // Insert through the generated class: proves IsAutoIncrement and DbType are correct,
        // because a wrong key mapping fails here while passing layers 1 and 2.
        object entity = Activator.CreateInstance(speciesType, [true])!;
        speciesType.GetProperty("Name")!.SetValue(entity, "Snow Leopard");
        // SQLite has no native boolean type; the emitter maps INTEGER columns to Int64, so
        // IsEndangered is a `long` property and must be set as one.
        speciesType.GetProperty("IsEndangered")!.SetValue(entity, 1L);

        object adapter = Activator.CreateInstance(
            typeof(DataClassAdapter<>).MakeGenericType(speciesType), [cnxn])!;

        var saveTask = (Task<bool>)adapter.GetType()
            .GetMethod("Save", [speciesType])!
            .Invoke(adapter, [entity])!;

        Assert.True(await saveTask);

        long assignedId = (long)speciesType.GetProperty("SpeciesId")!.GetValue(entity)!;
        Assert.True(assignedId > 0, "Identity value was not selected back after insert.");
    }

    // ---- Nullable ref-types regression guard -----------------------------------
    //
    // The three layers above all run with the default (ProjectProbe-detected) nullable-refs
    // setting, which resolves to false in a temp directory with no .csproj — so they never emit
    // a single "string?" and never exercise CSharpEntityEmitter's "#nullable enable" line at all.
    // A prior task discovered that a file headed "// <auto-generated>" disables the compiler's
    // nullable annotation context, so any "string?" the type mapper bakes in raises CS8669 unless
    // the emitter states "#nullable enable" itself. That fix was proven with a scratch build that
    // no longer exists; nothing here would have caught its removal. These tests explicitly pass
    // --nullable-refs true (bypassing ProjectProbe) to force the path and pin it down for good.

    [Theory]
    [InlineData("Species")]
    [InlineData("Animal")]
    [InlineData("Exhibit")]
    [InlineData("Zookeeper")]
    [InlineData("FeedingSchedule")]
    public void Generated_text_with_nullable_refs_matches_the_golden_file(string className)
    {
        string actual = File.ReadAllText(Path.Combine(_nullableEntitiesDir, $"{className}.g.cs"))
            .ReplaceLineEndings("\n");
        string expectedPath = Path.Combine(
            AppContext.BaseDirectory, "Golden", "Expected", "nullable", $"{className}.g.cs.txt");
        string expected = File.ReadAllText(expectedPath).ReplaceLineEndings("\n");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void Nullable_context_is_declared_between_the_autogenerated_header_and_the_usings()
    {
        string code = File.ReadAllText(Path.Combine(_nullableEntitiesDir, "Species.g.cs"));

        int headerEnd = code.IndexOf("</auto-generated>", StringComparison.Ordinal);
        int nullableIdx = code.IndexOf("#nullable enable", StringComparison.Ordinal);
        int usingIdx = code.IndexOf("using System;", StringComparison.Ordinal);

        Assert.True(headerEnd >= 0, "auto-generated header missing.");
        Assert.True(nullableIdx > headerEnd, "#nullable enable must come after the auto-generated header.");
        Assert.True(usingIdx > nullableIdx, "#nullable enable must come before the using directives.");
    }

    [Fact]
    public void Nullable_columns_emit_string_and_non_nullable_columns_do_not()
    {
        string species = File.ReadAllText(Path.Combine(_nullableEntitiesDir, "Species.g.cs"));

        // Classification (TEXT, nullable) must be "string?"...
        Assert.Contains("public string? Classification", species);
        // ...while Name (TEXT NOT NULL) must stay a bare "string", never "string?".
        Assert.Contains("public string Name", species);
        Assert.DoesNotContain("public string? Name", species);
    }

    /// <summary>
    /// The actual regression guard: compiles the --nullable-refs true output the way a consumer
    /// project with <c>&lt;Nullable&gt;enable&lt;/Nullable&gt;</c> and
    /// <c>&lt;TreatWarningsAsErrors&gt;true&lt;/TreatWarningsAsErrors&gt;</c> would.
    /// <para>
    /// The guarantee under test is "generated code builds clean under Nullable=enable", not "the
    /// two specific nullable diagnostics we have already been bitten by do not fire". An earlier
    /// version of this test escalated only CS8669 — the shape of the bug that was current when it
    /// was written — and consequently sailed straight past CS8618 ("non-nullable field must
    /// contain a non-null value when exiting constructor"), which every non-nullable
    /// string/byte[] backing field raised. So this now promotes *every* warning to an error via
    /// <see cref="ReportDiagnostic"/>, and the next member of the family is caught without anyone
    /// having to remember to add its code here.
    /// </para>
    /// </summary>
    [Fact]
    public void Generated_code_with_nullable_refs_compiles_with_warnings_as_errors()
    {
        CompilationResult result = Compile(
            "GeneratedZooNullable", NullableContextOptions.Enable, _nullableEntitiesDir,
            warningsAsErrors: true);

        Assert.True(result.Success,
            "Generated code did not compile clean under Nullable=enable + warnings-as-errors:\n" + result.Errors);
    }

    // ---- `field` keyword emit path ---------------------------------------------
    //
    // ProjectProbe auto-selects the `field` keyword for any net10.0 consumer, so this is the
    // default emit shape for a modern project — yet both passes above pin --field-keyword false,
    // and every FieldKeyword=true assertion in Emit/CSharpEntityEmitterTests is a string compare.
    // That left `get => field; set => SetFieldValue(ref field, value);` with zero compile
    // coverage: exactly the gap that let CS8669 through the first time. This pass generates with
    // --field-keyword true *and* --nullable-refs true, which together are what a net10.0 project
    // with <Nullable>enable</Nullable> actually gets, and routes it through the same Compile()
    // helper with the same warnings-as-errors escalation.

    [Theory]
    [InlineData("Species")]
    [InlineData("Animal")]
    [InlineData("Exhibit")]
    [InlineData("Zookeeper")]
    [InlineData("FeedingSchedule")]
    public void Generated_text_with_field_keyword_matches_the_golden_file(string className)
    {
        string actual = File.ReadAllText(Path.Combine(_fieldEntitiesDir, $"{className}.g.cs"))
            .ReplaceLineEndings("\n");
        string expectedPath = Path.Combine(
            AppContext.BaseDirectory, "Golden", "Expected", "field", $"{className}.g.cs.txt");
        string expected = File.ReadAllText(expectedPath).ReplaceLineEndings("\n");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void Field_keyword_output_declares_no_backing_fields()
    {
        string species = File.ReadAllText(Path.Combine(_fieldEntitiesDir, "Species.g.cs"));

        Assert.Contains("get => field; set => SetFieldValue(ref field, value);", species);
        Assert.DoesNotContain("private long _speciesId", species);
        Assert.DoesNotContain("private string _name", species);
    }

    /// <summary>
    /// The compile guard for the `field` path. Needs a C# 14 parse option, because `field` as a
    /// keyword (and `ref field` in particular) does not exist in earlier language versions.
    /// </summary>
    [Fact]
    public void Generated_code_with_field_keyword_compiles_with_warnings_as_errors()
    {
        CompilationResult result = Compile(
            "GeneratedZooField", NullableContextOptions.Enable, _fieldEntitiesDir,
            warningsAsErrors: true, languageVersion: LanguageVersion.Preview);

        Assert.True(result.Success,
            "Generated `field`-keyword code did not compile clean under Nullable=enable + " +
            "warnings-as-errors:\n" + result.Errors);
    }

    // ---- C# keyword identifiers ------------------------------------------------------
    //
    // NamingEngineTests pins the escaping rule itself; this proves the escaped identifier
    // survives everything downstream of it — the file name, the [Obsolete] message, the
    // pluralized wrapper property, the DataClassAdapter<T> type argument — and still compiles.
    // Uses --naming-style preserve, the mode that bypasses PascalCasing and so is the only way
    // a lower-case reserved word reaches an emitter intact.

    /// <summary>
    /// Two tables, each carrying a different half of the problem:
    /// <c>event</c> is a reserved word (and its columns include <c>class</c>, <c>lock</c>, the
    /// contextual <c>value</c>, and the contextual <c>field</c>), while <c>orders</c> is an
    /// entirely ordinary lower-case table name — the common case under
    /// <c>--naming-style preserve</c>, and the one that raises CS8981.
    /// </summary>
    private const string KeywordDdl = """
        CREATE TABLE "event" (
            "id"    INTEGER PRIMARY KEY AUTOINCREMENT,
            "class" TEXT NOT NULL,
            "lock"  INTEGER NOT NULL,
            "value" TEXT,
            "field" TEXT NOT NULL
        );
        CREATE TABLE "orders" (
            "id"    INTEGER PRIMARY KEY AUTOINCREMENT,
            "total" INTEGER NOT NULL
        );
        """;

    private async Task<string> CreateKeywordDatabase(string name)
    {
        string conn = $"Data Source={Path.Combine(_dir, name + ".db")}";

        await using (var cnxn = new SqliteConnection(conn))
        {
            await cnxn.OpenAsync(TestContext.Current.CancellationToken);
            await using var cmd = cnxn.CreateCommand();
            cmd.CommandText = KeywordDdl;
            await cmd.ExecuteNonQueryAsync(TestContext.Current.CancellationToken);
        }

        SqliteConnection.ClearAllPools();
        return conn;
    }

    private string[] KeywordArgs(string conn, string outDir, string fieldKeyword) =>
    [
        "generate",
        "--provider", "sqlite",
        "--connection", conn,
        // A keyword in a namespace segment is the same defect one level up from the class name,
        // and the namespace reaches both emitters, so it is pinned on the pass that compiles.
        "--namespace", "Zoo.lock.Keywords",
        "--out", outDir,
        // The wrapper's own class name never travelled through the naming layer, so
        // `--wrapper-class lock` used to emit `public partial class lock : DatabaseWrapper`.
        "--wrapper-class", "lock",
        "--naming-style", "preserve",
        "--singularize", "false",
        "--field-keyword", fieldKeyword,
        "--nullable-refs", "true",
        "--config-file", Path.Combine(_dir, "none.json")
    ];

    [Fact]
    public async Task Keyword_named_tables_and_columns_compile()
    {
        string conn = await CreateKeywordDatabase("keywords");
        string outDir = Path.Combine(_dir, "EntitiesKeyword");

        Assert.Equal(0, await Program.Main(KeywordArgs(conn, outDir, "false")));

        string code = File.ReadAllText(Path.Combine(outDir, "@event.g.cs"));

        Assert.Contains("class @event", code);
        Assert.Contains("@class", code);
        Assert.Contains("@lock", code);
        // Contextual keywords: legal as identifiers, so they must stay bare.
        Assert.Contains("public string? value", code);
        Assert.DoesNotContain("@value", code);
        Assert.Contains("public string field", code);
        // The @ is an escape, not part of the name: it must never reach a string literal, and it
        // must not be carried into a derived identifier either ("_@class" is not an identifier).
        Assert.Contains("[DataItem(\"event\")]", code);
        Assert.Contains("[DataField(\"class\"", code);
        Assert.Contains("private string _class", code);
        Assert.DoesNotContain("_@", code);

        // Namespace segments are identifiers too, and both emitters write the namespace.
        Assert.Contains("namespace Zoo.@lock.Keywords;", code);

        string wrapper = File.ReadAllText(Path.Combine(outDir, "@lock.g.cs"));
        Assert.Contains("public partial class @lock : DatabaseWrapper", wrapper);
        Assert.Contains("namespace Zoo.@lock.Keywords;", wrapper);

        // CS8981: an ordinary lower-case table name under preserve is a type name made only of
        // lower-case ASCII, which fails a TreatWarningsAsErrors build unless the generated file
        // says otherwise. An escaped name (@event) is exempt, so it must not carry the pragma.
        string orders = File.ReadAllText(Path.Combine(outDir, "orders.g.cs"));
        Assert.Contains("#pragma warning disable CS8981", orders);
        Assert.DoesNotContain("#pragma warning disable CS8981", code);

        CompilationResult result = Compile(
            "GeneratedKeywords", NullableContextOptions.Enable, outDir, warningsAsErrors: true);

        Assert.True(result.Success, "Keyword-escaped output did not compile:\n" + result.Errors);
    }

    /// <summary>
    /// A column named <c>field</c> under <c>--field-keyword true</c> — the shape
    /// <see cref="Zonkey.Scaffold.Emit.ProjectProbe"/> selects by itself for a net10.0 consumer.
    /// <c>field</c> is a legal identifier, so it is deliberately not escaped; but inside a
    /// property accessor it binds to the synthesized backing field, which makes every
    /// <c>get =&gt; field;</c> in the <em>whole class</em> ambiguous (CS9258), not just the
    /// offending property's. So the fallback has to be class-wide, and this test pins both
    /// halves: the affected class drops to explicit backing fields, and its sibling — same run,
    /// same options, no such column — still uses the keyword.
    /// </summary>
    [Fact]
    public async Task A_column_named_field_falls_back_to_explicit_backing_fields()
    {
        string conn = await CreateKeywordDatabase("fieldcolumn");
        string outDir = Path.Combine(_dir, "EntitiesFieldColumn");

        Assert.Equal(0, await Program.Main(KeywordArgs(conn, outDir, "true")));

        string code = File.ReadAllText(Path.Combine(outDir, "@event.g.cs"));
        Assert.Contains("private string _field = null!;", code);
        Assert.DoesNotContain("get => field;", code);

        string orders = File.ReadAllText(Path.Combine(outDir, "orders.g.cs"));
        Assert.Contains("get => field;", orders);
        Assert.DoesNotContain("private long _id", orders);

        CompilationResult result = Compile(
            "GeneratedFieldColumn", NullableContextOptions.Enable, outDir,
            warningsAsErrors: true, languageVersion: LanguageVersion.Preview);

        Assert.True(result.Success,
            "Output for a table with a column named `field` did not compile:\n" + result.Errors);
    }

    // ---- shared compile helper --------------------------------------------------

    private readonly record struct CompilationResult(bool Success, string Errors, byte[] AssemblyBytes)
    {
        public Assembly Load() => Assembly.Load(AssemblyBytes);
    }

    /// <summary>
    /// The only warnings exempted from the blanket escalation, and both are properties of the
    /// *test host's* reference set rather than of the generated code:
    /// CS1701/CS1702 are assembly-reference version unification notices, raised because this
    /// compilation is handed every assembly the xunit host happens to have loaded. The generated
    /// code cannot cause or avoid them. Every diagnostic that a generated file can actually
    /// provoke — the whole CS86xx nullable family included — stays an error.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, ReportDiagnostic> ToleratedWarnings =
        new Dictionary<string, ReportDiagnostic>
        {
            ["CS1701"] = ReportDiagnostic.Suppress,
            ["CS1702"] = ReportDiagnostic.Suppress,
        };

    /// <summary>
    /// Compiles every generated *.g.cs file in <paramref name="sourceDir"/> against the current
    /// AppDomain's assemblies (which already includes Zonkey.Data via the test project's
    /// ProjectReference). Shared by layer 2 (checks success/errors only), layer 3 (also loads the
    /// resulting assembly to exercise it at runtime), and every regression guard, so the Roslyn
    /// compilation logic exists exactly once regardless of which variant of the generated output
    /// is under test.
    /// </summary>
    /// <param name="warningsAsErrors">
    /// Promotes every warning to an error, i.e. compiles the way a consumer project with
    /// <c>TreatWarningsAsErrors</c> would. Deliberately general rather than an allow-list of
    /// diagnostic codes: an allow-list only ever guards the bug that was known when it was
    /// written. See <see cref="ToleratedWarnings"/> for the two carve-outs and why they are safe.
    /// <para>
    /// Required rather than defaulted, and true at all six call sites. It used to default to
    /// false, and two passes — including the default emit shape — silently opted out of the
    /// guarantee the other four asserted. A required parameter makes a future call site state its
    /// choice instead of inheriting the weaker one by omission.
    /// </para>
    /// </param>
    /// <param name="languageVersion">
    /// C# 14 (<see cref="LanguageVersion.Preview"/>) is required for the `field` keyword path;
    /// everything else compiles under the default.
    /// </param>
    private CompilationResult Compile(
        string assemblyName,
        NullableContextOptions nullableContext,
        string sourceDir,
        bool warningsAsErrors,
        LanguageVersion languageVersion = LanguageVersion.Latest)
    {
        var parseOptions = new CSharpParseOptions(languageVersion);

        var trees = Directory
            .EnumerateFiles(sourceDir, "*.g.cs")
            .OrderBy(f => f, StringComparer.Ordinal)
            .Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f), parseOptions, path: f))
            .ToList();

        // AppDomain.CurrentDomain.GetAssemblies() only reflects assemblies some earlier code path
        // has already touched. Running this whole test class together happens to touch
        // Zonkey.Data early (the round-trip test references DataClassAdapter<> directly), but
        // running this test filtered/in isolation does not — nothing in this method's own body
        // otherwise names a Zonkey.Data type, so the snapshot below would omit Zonkey.Data.dll
        // entirely and every generated file would fail with unrelated "DataField"/"SetFieldValue"
        // errors instead of the diagnostic the test actually cares about. Resolve
        // Zonkey.Data's location directly from a known type rather than trusting it is already
        // loaded, so this helper is correct regardless of what else has (or hasn't) run first.
        Assembly zonkeyData = typeof(Zonkey.ObjectModel.DataClass).Assembly;

        var references = AppDomain.CurrentDomain
            .GetAssemblies()
            .Append(zonkeyData)
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Distinct()
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
            nullableContextOptions: nullableContext);

        if (warningsAsErrors)
        {
            options = options
                .WithGeneralDiagnosticOption(ReportDiagnostic.Error)
                .WithSpecificDiagnosticOptions(ToleratedWarnings);
        }

        var compilation = CSharpCompilation.Create(assemblyName, trees, references, options);

        using var ms = new MemoryStream();
        EmitResult result = compilation.Emit(ms);

        string errors = string.Join("\n", result.Diagnostics
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .Select(d => d.ToString()));

        return new CompilationResult(result.Success, errors, ms.ToArray());
    }
}
