using Xunit;
using Zonkey.Scaffold.Config;
using Zonkey.Scaffold.Emit;
using Zonkey.Scaffold.Io;
using Zonkey.Scaffold.Options;

namespace Zonkey.Scaffold.Tests;

/// <summary>
/// Pins the defects found in review of the scaffold PR. Each one shipped, compiled, and passed
/// the suite as it stood, so each gets the test that would have caught it.
/// </summary>
public class RegressionTests
{
    /// <summary>
    /// IConfiguration's command-line provider drops a switch with no value, so `--dry-run` left
    /// DryRun false and the tool wrote the files it was told not to. Only `--dry-run true` worked.
    /// </summary>
    [Theory]
    [InlineData(new[] { "--dry-run" }, true)]
    [InlineData(new[] { "--dry-run", "true" }, true)]
    [InlineData(new[] { "--dry-run", "false" }, false)]
    [InlineData(new string[0], false)]
    public void Bare_boolean_switch_is_true(string[] args, bool expected)
    {
        ScaffoldOptions o = ConfigurationLoader.Load(args, Path.GetTempPath());
        Assert.Equal(expected, o.DryRun);
    }

    /// <summary>A bare flag must not swallow the argument that follows it.</summary>
    [Fact]
    public void Bare_switch_does_not_consume_the_next_argument()
    {
        ScaffoldOptions o = ConfigurationLoader.Load(
            ["--dry-run", "--provider", "pgsql"], Path.GetTempPath());

        Assert.True(o.DryRun);
        Assert.Equal("pgsql", o.Provider);
    }

    /// <summary>
    /// The --schema alias mapped to the indexed key "Schemas:0", which made IConfiguration treat
    /// Schemas as having children; config["Schemas"] then returned null, the delimited-scalar
    /// split never ran, and `--schema public;archive` became one schema of that literal name.
    /// </summary>
    [Fact]
    public void Schema_alias_accepts_a_delimited_list()
    {
        ScaffoldOptions o = ConfigurationLoader.Load(
            ["--schema", "public;archive"], Path.GetTempPath());

        Assert.Equal(["public", "archive"], o.Schemas);
    }

    /// <summary>The indexed form has to keep working alongside it.</summary>
    [Fact]
    public void Indexed_schema_keys_still_bind()
    {
        ScaffoldOptions o = ConfigurationLoader.Load(
            ["--Schemas:0", "public", "--Schemas:1", "archive"], Path.GetTempPath());

        Assert.Equal(["public", "archive"], o.Schemas);
    }

    /// <summary>
    /// IsGenerated only knew the C# marker, so a VB file looked hand-written and the second run
    /// against the same output directory refused to overwrite the tool's own output.
    /// </summary>
    [Theory]
    [InlineData("// <auto-generated>\npublic class X { }")]
    [InlineData("' <auto-generated>\nPublic Class X\nEnd Class")]
    public void Both_language_markers_are_recognized(string content)
    {
        string path = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        File.WriteAllText(path, content);

        try { Assert.True(GeneratedFileWriter.IsGenerated(path)); }
        finally { File.Delete(path); }
    }

    [Fact]
    public void A_hand_written_file_is_still_refused()
    {
        string path = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        File.WriteAllText(path, "// something a person wrote\npublic class X { }");

        try { Assert.False(GeneratedFileWriter.IsGenerated(path)); }
        finally { File.Delete(path); }
    }

    /// <summary>
    /// The relation loaders emitted .HasValue/.Value for any nullable key. Those exist only on
    /// Nullable&lt;T&gt;, so a nullable string key — a country code, a SKU — produced source that
    /// did not compile.
    /// </summary>
    [Fact]
    public void Nullable_reference_key_uses_a_null_check_not_HasValue()
    {
        string source = EmitLoaderFor("string");

        Assert.Contains("!= null", source);
        Assert.DoesNotContain(".HasValue", source);
        Assert.DoesNotContain("!.Value", source);
    }

    /// <summary>Value-type keys must keep using Nullable&lt;T&gt;'s members.</summary>
    [Fact]
    public void Nullable_value_key_still_uses_HasValue()
    {
        string source = EmitLoaderFor("int");

        Assert.Contains(".HasValue", source);
        Assert.Contains("!.Value", source);
    }

    private static string EmitLoaderFor(string keyClrType)
    {
        var owner = new EntityModel { ClassName = "Customer", TableName = "customers" };
        var relation = new RelationModel
        {
            MemberName = "Region",
            TypeName = "Region",
            IsCollection = false,
            Origin = "public.customers.region_id -> public.regions",
            CanLoad = true,
            LocalKey = "RegionId",
            ForeignKey = "RegionId",
            KeyClrType = keyClrType,
            LocalKeyIsNullable = true,
            ForeignKeyIsNullable = false,
        };

        return new CSharpRelationsEmitter().Emit(
            "Region",
            [new RelationLoader(owner, relation)],
            new EntityEmitOptions { Namespace = "Shop.Data", NullableRefs = true });
    }
}
