using System.Text;
using Zonkey.Scaffold.Diagnostics;

namespace Zonkey.Scaffold.Emit;

public sealed class CSharpEntityEmitter
{
    public const string AutoGeneratedHeader = "// <auto-generated>";

    public string Emit(EntityModel model, EntityEmitOptions options)
    {
        options = ResolveFieldKeyword(model, options);

        var w = new IndentedWriter();

        EmitHeader(w);

        // A file starting with "// <auto-generated>" disables the compiler's nullable
        // annotation context, so any '?' the type mapper baked into a ClrType (e.g. "string?")
        // would otherwise raise CS8669. Declaring the context here is the only fix; the
        // emitter itself never decides nullability, it just needs to state the context it
        // was written for.
        if (options.NullableRefs)
        {
            w.Line("#nullable enable");
            w.Blank();
        }

        EmitLowerCaseNameSuppression(w, model.ClassName);

        w.Line("using System;");

        // Not assumed from ImplicitUsings: the generated file may land in a project without it.
        if (model.Relations.Any(r => r.IsCollection))
            w.Line("using System.Collections.Generic;");

        w.Line("using System.Data;");
        w.Line("using Zonkey.ObjectModel;");
        w.Blank();

        // The model.s own namespace wins; the run-wide option is the default.
        string? ns = model.Namespace ?? options.Namespace;

        if (!string.IsNullOrWhiteSpace(ns))
        {
            w.Line($"namespace {ns};");
            w.Blank();
        }

        w.Line(DataItemAttribute(model));
        w.Open(ClassDeclaration(model, options));

        if (model.IsReadOnly)
        {
            EmitReadOnlyProperties(w, model, options);
        }
        else
        {
            if (options.PrivateFieldsAtTop && !options.FieldKeyword)
                EmitPrivateFields(w, model, options);

            EmitConstructors(w, model);
            EmitProperties(w, model, options);
        }

        EmitRelations(w, model, options);

        w.Close();
        return w.ToString();
    }

    /// <summary>
    /// Emits the graph members, which carry no <c>[DataField]</c> and so are invisible to the
    /// adapter. Nothing here loads anything — that is the caller's second query.
    /// </summary>
    private static void EmitRelations(IndentedWriter w, EntityModel model, EntityEmitOptions options)
    {
        if (model.Relations.Count == 0) return;

        w.Blank();
        w.Line("// Related data. These have no [DataField], so the adapter never reads or writes");
        w.Line("// them — nothing is loaded until you fill them yourself. See");
        w.Line("// docs/modeling-relationships.md.");

        foreach (RelationModel r in model.Relations)
        {
            w.Line($"// {r.Origin}");

            if (r.IsCollection)
                w.Line($"public List<{r.TypeName}> {r.MemberName} {{ get; }} = new();");
            else
                w.Line($"public {r.TypeName}{(options.NullableRefs ? "?" : "")} {r.MemberName} {{ get; set; }}");
        }
    }

    /// <summary>
    /// Drops the whole class to explicit backing fields when any property is named <c>field</c>.
    /// </summary>
    /// <remarks>
    /// Inside an accessor <c>field</c> binds to the synthesized backing field, so a member of that
    /// name makes every <c>get =&gt; field;</c> in the class ambiguous (CS9258) — every property,
    /// not just the offending one, so it cannot be a per-property fallback. <c>@field</c> does not
    /// help: the member is still named <c>field</c>.
    /// </remarks>
    private static EntityEmitOptions ResolveFieldKeyword(EntityModel model, EntityEmitOptions options)
    {
        bool resolved = UsesFieldKeyword(model, options.FieldKeyword);

        return resolved == options.FieldKeyword ? options : options with { FieldKeyword = resolved };
    }

    private static bool UsesFieldKeyword(EntityModel model, bool fieldKeyword)
        => fieldKeyword && !model.Properties.Any(p => p.Name.TrimStart('@') == "field");

    /// <summary>
    /// Suppresses CS8981 when the class name is made only of lower-case ASCII letters — which
    /// <c>Naming:Style=preserve</c> against a <c>lower_snake_case</c> schema produces for every
    /// table. Emitted only where it applies.
    /// </summary>
    private static void EmitLowerCaseNameSuppression(IndentedWriter w, string className)
    {
        if (!Naming.NamingEngine.IsAllLowerCaseAscii(className)) return;

        w.Line($"// The class name is '{className}', taken verbatim from the schema under");
        w.Line("// --naming-style preserve. CS8981 flags all-lower-case type names as possible");
        w.Line("// future keywords; renaming the class is the caller's decision, not this tool's.");
        w.Line("#pragma warning disable CS8981");
        w.Blank();
    }

    private static void EmitHeader(IndentedWriter w)
    {
        // No timestamp and no tool version: regenerating an unchanged schema must produce
        // byte-identical output so a diff shows only the schema change.
        w.Line(AutoGeneratedHeader);
        w.Line("//     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("//     Add your own members in a separate partial class file.");
        w.Line("// </auto-generated>");
        w.Blank();
    }

    private static string DataItemAttribute(EntityModel model)
    {
        var sb = new StringBuilder($"[DataItem(\"{Escape(model.TableName)}\"");

        if (!string.IsNullOrEmpty(model.SchemaName))
            sb.Append($", SchemaName = \"{Escape(model.SchemaName)}\"");

        if (!string.IsNullOrEmpty(model.SaveToTable))
            sb.Append($", SaveToTable = \"{Escape(model.SaveToTable)}\"");

        return sb.Append(")]").ToString();
    }

    private static string ClassDeclaration(EntityModel model, EntityEmitOptions options)
    {
        string partial = options.PartialClasses ? "partial " : "";

        // A view or key-less table cannot be saved, so it is emitted without the DataClass
        // base: read-only by construction rather than by convention.
        string baseType = model.IsReadOnly ? "" : " : DataClass";

        return $"public {partial}class {model.ClassName}{baseType}";
    }

    private static void EmitPrivateFields(IndentedWriter w, EntityModel model, EntityEmitOptions options)
    {
        foreach (PropertyModel p in model.Properties)
            w.Line($"private {p.ClrType} {BackingField(p)}{NullForgiving(p, options)};");

        w.Blank();
    }

    private static void EmitConstructors(IndentedWriter w, EntityModel model)
    {
        w.Line($"public {model.ClassName}(bool addingNew) : base(addingNew) {{ }}");
        w.Blank();

        // Required by the DataClassAdapter materializer, which constructs through emitted IL
        // and never sees this attribute. Obsolete-as-error stops application code from calling
        // it, because base(false) yields Detached and saving a Detached object throws.
        w.Line($"[Obsolete(\"Required by the DataClassAdapter materializer; " +
               $"use {Escape(model.ClassName)}(bool addingNew) in code.\", true)]");
        w.Line($"public {model.ClassName}() : this(false) {{ }}");
        w.Blank();
    }

    private static void EmitProperties(IndentedWriter w, EntityModel model, EntityEmitOptions options)
    {
        for (int i = 0; i < model.Properties.Count; i++)
        {
            PropertyModel p = model.Properties[i];

            w.Line(DataFieldAttribute(p));

            string virtualKeyword = options.VirtualProperties ? "virtual " : "";

            if (options.FieldKeyword)
            {
                // A property initializer on a `field`-backed property assigns the backing field
                // directly, not through the setter — so this is the `field`-mode equivalent of
                // initializing the private field, and it does not run SetFieldValue (which would
                // dirty a freshly materialized row).
                string initializer = NullForgiving(p, options) is { Length: > 0 } n ? n + ";" : "";

                w.Line($"public {virtualKeyword}{p.ClrType} {p.Name} " +
                       "{ get => field; set => SetFieldValue(ref field, value); }" + initializer);
            }
            else
            {
                string backing = BackingField(p);
                w.Line($"public {virtualKeyword}{p.ClrType} {p.Name} " +
                       $"{{ get => {backing}; set => SetFieldValue(ref {backing}, value); }}");

                if (!options.PrivateFieldsAtTop)
                    w.Line($"private {p.ClrType} {backing}{NullForgiving(p, options)};");
            }

            if (i < model.Properties.Count - 1) w.Blank();
        }
    }

    private static void EmitReadOnlyProperties(IndentedWriter w, EntityModel model, EntityEmitOptions options)
    {
        for (int i = 0; i < model.Properties.Count; i++)
        {
            PropertyModel p = model.Properties[i];
            string initializer = NullForgiving(p, options) is { Length: > 0 } n ? n + ";" : "";

            w.Line(DataFieldAttribute(p));
            w.Line($"public {p.ClrType} {p.Name} {{ get; set; }}" + initializer);

            if (i < model.Properties.Count - 1) w.Blank();
        }
    }

    private static string DataFieldAttribute(PropertyModel p)
    {
        var sb = new StringBuilder(
            $"[DataField(\"{Escape(p.ColumnName)}\", DbType.{p.DbType}, {(p.IsNullable ? "true" : "false")}");

        if (p.Length is > 0 && IsSized(p.DbType))
            sb.Append($", Length = {p.Length}");

        if (p.IsKey) sb.Append(", IsKeyField = true");
        if (p.IsIdentity) sb.Append(", IsAutoIncrement = true");
        if (p.IsRowVersion) sb.Append(", IsRowVersion = true");

        if (!string.IsNullOrEmpty(p.SequenceName))
            sb.Append($", SequenceName = \"{Escape(p.SequenceName)}\"");

        if (!string.IsNullOrEmpty(p.DateTimeKind))
            sb.Append($", DateTimeKind = DateTimeKind.{p.DateTimeKind}");

        return sb.Append(")]").ToString();
    }

    internal static bool IsSized(string dbType)
        => dbType is "String" or "StringFixedLength" or "AnsiString"
                  or "AnsiStringFixedLength" or "Binary";

    /// <summary>
    /// Derives the private backing field's name from the property's.
    /// </summary>
    /// <remarks>
    /// A leading <c>@</c> is stripped first, because it is a lexical escape rather than part of
    /// the name: a property named <c>@class</c> would otherwise back onto <c>_@class</c>, which
    /// is not an identifier at all and does not compile. The underscore prefix already makes the
    /// result safe — no C# keyword starts with one — so nothing needs re-escaping here.
    /// <para>
    /// A name that is nothing *but* the escape is refused rather than indexed into.
    /// <see cref="Naming.NamingEngine"/> rejects it earlier and names the column, so this is the
    /// backstop for a model built by hand; without it the tool exits 2 ("unexpected error") on an
    /// input it can describe exactly.
    /// </para>
    /// <para>
    /// Public because <c>ScaffoldPipeline.DetectCollisions</c> has to refuse two properties whose
    /// backing fields would collide (<c>Label</c> and <c>label</c> both give <c>_label</c>), and
    /// deriving that name a second time there would be a rule in two places free to drift apart —
    /// which is the shape of the bug being fixed, not a fix for it.
    /// </para>
    /// </remarks>
    public static string BackingField(PropertyModel p)
    {
        string name = p.Name.TrimStart('@');

        if (name.Length == 0)
            throw new ScaffoldException(
                $"Column '{p.ColumnName}' maps to the property name '{p.Name}', which is not a " +
                "valid C# identifier. Rename the column, or rename the property afterwards.");

        return "_" + char.ToLowerInvariant(name[0]) + name[1..];
    }

    /// <summary>
    /// Returns <c>" = null!"</c> for a storage location the compiler would otherwise flag as
    /// definitely-unassigned, and the empty string everywhere else.
    /// <para>
    /// Under <c>#nullable enable</c> a non-nullable reference-typed field that no constructor
    /// assigns raises CS8618 (CS9264 for the <c>field</c>-keyword form), so every emitted entity
    /// produced N warnings per entity in a normal consumer project and failed outright under
    /// <c>TreatWarningsAsErrors</c>. A materialized row always has its columns written by the
    /// adapter before anything reads them, and a NOT NULL column can never legitimately hold
    /// null, so <c>null!</c> states exactly what is true: the value is supplied out of band.
    /// Making the property nullable instead would be a lie about the schema, and <c>required</c>
    /// would break the parameterless constructor the materializer needs.
    /// </para>
    /// <para>
    /// Deliberately narrow: a value type is never affected (it is definitely-assigned by
    /// default), a type the mapper already annotated with <c>?</c> is never affected (it is
    /// legally null), and nothing at all changes when nullable reference types are off, because
    /// the diagnostic does not exist in that context.
    /// </para>
    /// </summary>
    private static string NullForgiving(PropertyModel p, EntityEmitOptions options)
    {
        if (!options.NullableRefs) return "";
        if (p.ClrType.EndsWith('?')) return "";

        // The mapper's whole reference-typed vocabulary: string (and its fixed-length variant)
        // and byte[]. Arrays are matched structurally so a future mapper adding e.g. char[]
        // is covered without another edit here.
        bool isReferenceType = p.ClrType.EndsWith("[]", StringComparison.Ordinal)
                            || p.ClrType is "string" or "object";

        return isReferenceType ? " = null!" : "";
    }

    /// <summary>
    /// Escapes a value that will be interpolated into a regular (non-verbatim) C# string
    /// literal. Database identifiers can legally contain double quotes (SQLite, PostgreSQL,
    /// and SQL Server all permit them in quoted identifiers), so every identifier reaching a
    /// string literal must be routed through here or the emitted source fails to compile.
    /// </summary>
    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
