namespace Zonkey.Scaffold.Emit;

/// <summary>One owner entity and one of its relations — the input to a single Fill method.</summary>
public sealed record RelationLoader(EntityModel Owner, RelationModel Relation);

/// <summary>
/// Emits <c>{Entity}Extensions</c>: the batched loaders for every relation whose rows come from
/// that entity.
/// </summary>
/// <remarks>
/// The methods extend the adapter of the type being <em>queried</em>, and take the owners whose
/// members get filled — <c>db.OrderDetails.FillOrderDetailsFor(orders)</c>. That way the caller
/// supplies the adapter, so the query inherits their transaction, timeout and identifier settings,
/// and the wrapper's adapter cache is reused. Nothing here constructs an adapter, which is what
/// keeps the generated code out of connection-lifetime management entirely.
/// <para>
/// Every method is one query for any number of owners, then an in-memory join. The key array is
/// assigned to a local first because the expression translator folds a variable to a value but
/// will not evaluate an inline expression in the <c>Contains</c> argument. <c>Contains</c> rather
/// than <c>SqlInInt</c>: the <c>SqlIn*</c> helpers are <c>[Obsolete]</c> as of v7 — the translator
/// now parameterizes or inlines the list by itself, and it works for any key type.
/// </para>
/// </remarks>
public sealed class CSharpRelationsEmitter
{
    /// <summary>Groups every relation in the plan by the entity whose adapter will load it.</summary>
    public static IEnumerable<(string TypeName, List<RelationLoader> Loaders)> Group(
        IEnumerable<EntityModel> entities)
        => entities
            .SelectMany(owner => owner.Relations
                .Where(r => r.CanLoad)
                .Select(r => new RelationLoader(owner, r)))
            .GroupBy(l => l.Relation.TypeName, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => (g.Key, g.ToList()));

    public string Emit(string typeName, List<RelationLoader> loaders, EntityEmitOptions options)
    {
        var w = new IndentedWriter();

        w.Line(CSharpEntityEmitter.AutoGeneratedHeader);
        w.Line("//     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("// </auto-generated>");
        w.Blank();

        if (options.NullableRefs)
        {
            w.Line("#nullable enable");
            w.Blank();
        }

        w.Line("using System.Collections.Generic;");
        w.Line("using System.Linq;");
        w.Line("using System.Threading.Tasks;");
        w.Line("using Zonkey;");
        w.Blank();

        if (!string.IsNullOrWhiteSpace(options.Namespace))
        {
            w.Line($"namespace {options.Namespace};");
            w.Blank();
        }

        w.Open($"public static class {typeName}Extensions");

        for (int i = 0; i < loaders.Count; i++)
        {
            if (i > 0) w.Blank();
            EmitLoader(w, typeName, loaders[i], options);
        }

        w.Close();
        return w.ToString();
    }

    private static void EmitLoader(
        IndentedWriter w, string typeName, RelationLoader loader, EntityEmitOptions options)
    {
        RelationModel r = loader.Relation;
        string owner = loader.Owner.ClassName;
        string method = $"Fill{r.MemberName.TrimStart('@')}For";
        string q = options.NullableRefs ? "?" : "";

        // The key array's element type follows the field being filtered, so a nullable queried
        // column yields a nullable element type — but only for value types. `string?` is the same
        // runtime type as `string`, and nulls are filtered out below either way.
        bool keyIsValueType = IsValueType(r.KeyClrType);
        bool boxKey = r.ForeignKeyIsNullable && keyIsValueType;
        string keyType = r.KeyClrType + (boxKey ? "?" : "");

        // Nullable value types and nullable reference types are unwrapped differently: `.HasValue`
        // and `.Value` exist only on Nullable<T>. Emitting them for a nullable string key — a
        // country code, a SKU — produced source that would not compile.
        string NotNull(string expr) => keyIsValueType ? $"{expr}.HasValue" : $"{expr} != null";
        string Unwrap(string expr) => keyIsValueType ? $"{expr}!.Value" : $"{expr}!";

        w.Line($"/// <summary>Fills <see cref=\"{owner}.{r.MemberName}\"/> for every owner, in one query.</summary>");
        w.Line($"/// <remarks>{r.Origin}</remarks>");
        w.Open($"public static async Task<int> {method}(this DataClassAdapter<{typeName}> adapter, " +
               $"IEnumerable<{owner}> owners)");

        w.Line($"var list = owners as IList<{owner}> ?? owners.ToList();");
        w.Line("if (list.Count == 0) return 0;");
        w.Blank();

        // Assigned to a local: the expression parser folds a variable to a value, but rejects an
        // inline expression in the SqlIn argument.
        string select = r.LocalKeyIsNullable
            ? $"list.Where(o => {NotNull($"o.{r.LocalKey}")}).Select(o => ({keyType}){Unwrap($"o.{r.LocalKey}")})"
            : $"list.Select(o => ({keyType})o.{r.LocalKey})";

        w.Line($"{keyType}[] keys = {select}.Distinct().ToArray();");
        w.Line("if (keys.Length == 0) return 0;");
        w.Blank();

        w.Line($"var loaded = new List<{typeName}>();");
        w.Line($"await adapter.Fill(loaded, x => keys.Contains(x.{r.ForeignKey}));");
        w.Blank();

        if (r.IsCollection)
        {
            w.Line($"var byKey = loaded.ToLookup(x => x.{r.ForeignKey});");
            w.Open($"foreach ({owner} item in list)");
            w.Line($"item.{r.MemberName}.Clear();");
            w.Line(r.LocalKeyIsNullable
                ? $"if ({NotNull($"item.{r.LocalKey}")}) item.{r.MemberName}.AddRange(byKey[({keyType}){Unwrap($"item.{r.LocalKey}")}]);"
                : $"item.{r.MemberName}.AddRange(byKey[({keyType})item.{r.LocalKey}]);");
            w.Close();
        }
        else
        {
            // First wins on a duplicate key: a malformed parent table must not throw here, where
            // the caller has no way to see which row was at fault.
            w.Line($"var byKey = new Dictionary<{r.KeyClrType}, {typeName}>();");
            w.Open($"foreach ({typeName} row in loaded)");
            w.Line(r.ForeignKeyIsNullable
                ? $"if ({NotNull($"row.{r.ForeignKey}")}) byKey[{Unwrap($"row.{r.ForeignKey}")}] = row;"
                : $"byKey[row.{r.ForeignKey}] = row;");
            w.Close();
            w.Blank();

            w.Open($"foreach ({owner} item in list)");
            w.Line(r.LocalKeyIsNullable
                ? $"item.{r.MemberName} = {NotNull($"item.{r.LocalKey}")} && " +
                  $"byKey.TryGetValue({Unwrap($"item.{r.LocalKey}")}, out {typeName}{q} found) ? found : null;"
                : $"item.{r.MemberName} = byKey.TryGetValue(item.{r.LocalKey}, " +
                  $"out {typeName}{q} found) ? found : null;");
            w.Close();
        }

        w.Blank();
        w.Line("return loaded.Count;");
        w.Close();
        w.Blank();

        w.Line($"/// <summary>Fills <see cref=\"{owner}.{r.MemberName}\"/> for one owner.</summary>");
        w.Line($"public static Task<int> {method}(this DataClassAdapter<{typeName}> adapter, {owner} owner)");
        w.Line($"    => adapter.{method}(new[] {{ owner }});");
    }

    private static bool IsValueType(string clrType) => clrType is
        "bool" or "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong"
        or "float" or "double" or "decimal" or "char" or "DateTime" or "DateTimeOffset"
        or "TimeSpan" or "Guid" or "DateOnly" or "TimeOnly";
}
