namespace Zonkey.Scaffold.Emit;

public sealed class WrapperModel
{
    public string ClassName { get; set; } = "AppDatabase";
    public string ConnectionName { get; set; } = "Default";
    public string? Namespace { get; set; }
    public bool PartialClasses { get; set; } = true;
    public List<WrapperEntry> Entries { get; set; } = new();
}

public sealed class WrapperEntry
{
    public string PropertyName { get; set; } = "";
    public string EntityClassName { get; set; } = "";

    /// <summary>
    /// The namespace the entity class is declared in, or <c>null</c> when it is the wrapper's own.
    /// </summary>
    /// <remarks>
    /// There is one wrapper per run and it names every entity type, so
    /// <c>--schema-disambiguation namespace</c> — which puts each schema's classes in a namespace
    /// of its own — is the case where a bare class name stops being enough to name the type. Two
    /// schemas' <c>Animal</c> are then two distinct types, and the wrapper has to say which one
    /// each adapter is for.
    /// </remarks>
    public string? EntityNamespace { get; set; }

    /// <summary>
    /// The entity type's full name — what makes two same-named classes from different schemas
    /// distinguishable to anything reasoning about the wrapper's members.
    /// </summary>
    public string EntityTypeName => string.IsNullOrEmpty(EntityNamespace)
        ? EntityClassName
        : $"{EntityNamespace}.{EntityClassName}";
}

/// <summary>
/// Emits the single named entry point. The per-entity properties are sugar over the inherited
/// generic Adapter&lt;T&gt;(), but they are what makes the generated layer discoverable — the
/// whole data model is legible in one file, which is the difference between scaffolding that
/// ends at runnable code and scaffolding that ends at a pile of classes.
/// </summary>
public sealed class CSharpWrapperEmitter
{
    public string Emit(WrapperModel model)
    {
        var w = new IndentedWriter();

        // No timestamp and no tool version: regenerating an unchanged schema must produce
        // byte-identical output so a diff shows only the schema change.
        w.Line(CSharpEntityEmitter.AutoGeneratedHeader);
        w.Line("//     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("//     Add your own members in a separate partial class file.");
        w.Line("// </auto-generated>");
        w.Blank();

        // The wrapper declares a type exactly as the entity emitter does, so an all-lower-case
        // --wrapper-class raises the same CS8981 and needs the same suppression. See the long
        // note on CSharpEntityEmitter.EmitLowerCaseNameSuppression for why this is suppressed in
        // the generated file rather than reported as a scaffold warning.
        if (Naming.NamingEngine.IsAllLowerCaseAscii(model.ClassName))
        {
            w.Line($"// The class name is '{model.ClassName}', as given by --wrapper-class.");
            w.Line("// CS8981 flags all-lower-case type names as possible future keywords.");
            w.Line("#pragma warning disable CS8981");
            w.Blank();
        }

        w.Line("using System.Data.Common;");
        w.Line("using Zonkey;");
        w.Line("using Zonkey.ObjectModel;");
        w.Blank();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            w.Line($"namespace {model.Namespace};");
            w.Blank();
        }

        string partial = model.PartialClasses ? "partial " : "";
        w.Open($"public {partial}class {model.ClassName} : DatabaseWrapper");

        w.Line($"public {model.ClassName}() : base(\"{Escape(model.ConnectionName)}\") {{ }}");
        w.Blank();
        w.Line($"public {model.ClassName}(DbConnection connection) : base(connection) {{ }}");

        foreach (WrapperEntry entry in model.Entries
                     .OrderBy(e => e.PropertyName, StringComparer.Ordinal))
        {
            string type = TypeReference(entry, model.Namespace);

            w.Blank();
            w.Line($"public DataClassAdapter<{type}> {entry.PropertyName} => Adapter<{type}>();");
        }

        w.Close();
        return w.ToString();
    }

    /// <summary>
    /// How this file has to spell an entity type: the bare class name for an entity that shares the
    /// wrapper's namespace, and a <c>global::</c>-qualified name for one that does not.
    /// </summary>
    /// <remarks>
    /// Only <c>--schema-disambiguation namespace</c> produces the second case, and there the bare
    /// name is not merely unqualified but ambiguous — two schemas' <c>Animal</c> are two types, and
    /// naming one of them is the entire point of that strategy. The alias qualifier is what makes
    /// the reference immune to capture: a generated class named <c>Zoo</c> in namespace
    /// <c>Zoo.Data</c> captures the leading segment of <c>Zoo.Data.Archive.Animal</c> and the file
    /// does not compile (CS0426, "the type name 'Data' does not exist in the type 'Zoo'" —
    /// reproduced, not assumed), while the <c>global::</c> form compiles. Emitted only where it is
    /// needed, so the ordinary single-namespace output is byte-identical to what it always was.
    /// </remarks>
    private static string TypeReference(WrapperEntry entry, string? wrapperNamespace)
        => string.IsNullOrEmpty(entry.EntityNamespace) ||
           string.Equals(entry.EntityNamespace, wrapperNamespace, StringComparison.Ordinal)
            ? entry.EntityClassName
            : $"global::{entry.EntityTypeName}";

    /// <summary>
    /// Escapes a value that will be interpolated into a regular (non-verbatim) C# string
    /// literal. The connection name is user-supplied config, not a compiler-controlled
    /// identifier, so it can legally contain a double quote or backslash; every such value
    /// reaching a string literal must be routed through here or the emitted source fails to
    /// compile (or worse, changes meaning). Duplicated from CSharpEntityEmitter rather than
    /// shared because that emitter keeps its helper private — promoting it to internal would
    /// mean editing a file this task must leave untouched, for one two-line method.
    /// </summary>
    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
