namespace Zonkey.Scaffold.Emit;

public sealed class WrapperModel
{
    public string ClassName { get; set; } = "AppDatabase";
    public string ConnectionName { get; set; } = "Default";
    public string? Namespace { get; set; }
    public bool PartialClasses { get; set; } = true;
    public List<WrapperEntry> Entries { get; set; } = new();
}

public sealed class WrapperEntry
{
    public string PropertyName { get; set; } = "";
    public string EntityClassName { get; set; } = "";
}

/// <summary>
/// Emits the single named entry point. The per-entity properties are sugar over the inherited
/// generic Adapter&lt;T&gt;(), but they are what makes the generated layer discoverable — the
/// whole data model is legible in one file, which is the difference between scaffolding that
/// ends at runnable code and scaffolding that ends at a pile of classes.
/// </summary>
public sealed class CSharpWrapperEmitter
{
    /// <summary>
    /// Every type this emitter names in the source it writes, by simple name. See
    /// <see cref="CSharpEntityEmitter.ReferencedTypeNames"/> for why the list exists and what
    /// keeps it honest.
    /// </summary>
    /// <remarks>
    /// The entity class names this emitter also writes are not here, and must not be: they are the
    /// types the same run declares, so a reference to one resolves to the class that was emitted.
    /// A generated class named after another generated class is a duplicate type name, which
    /// <c>EmittedSurface.Check</c> refuses outright.
    /// </remarks>
    public static readonly IReadOnlyList<string> ReferencedTypeNames =
    [
        "DatabaseWrapper",      // the base type
        "DbConnection",         // the connection-taking constructor's parameter
        "DataClassAdapter"      // every adapter property's type
    ];

    public string Emit(WrapperModel model)
    {
        var w = new IndentedWriter();

        // No timestamp and no tool version: regenerating an unchanged schema must produce
        // byte-identical output so a diff shows only the schema change.
        w.Line(CSharpEntityEmitter.AutoGeneratedHeader);
        w.Line("//     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("//     Add your own members in a separate partial class file.");
        w.Line("// </auto-generated>");
        w.Blank();

        // The wrapper declares a type exactly as the entity emitter does, so an all-lower-case
        // --wrapper-class raises the same CS8981 and needs the same suppression. See the long
        // note on CSharpEntityEmitter.EmitLowerCaseNameSuppression for why this is suppressed in
        // the generated file rather than reported as a scaffold warning.
        if (Naming.NamingEngine.IsAllLowerCaseAscii(model.ClassName))
        {
            w.Line($"// The class name is '{model.ClassName}', as given by --wrapper-class.");
            w.Line("// CS8981 flags all-lower-case type names as possible future keywords.");
            w.Line("#pragma warning disable CS8981");
            w.Blank();
        }

        w.Line("using System.Data.Common;");
        w.Line("using Zonkey;");
        w.Line("using Zonkey.ObjectModel;");
        w.Blank();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            w.Line($"namespace {model.Namespace};");
            w.Blank();
        }

        string partial = model.PartialClasses ? "partial " : "";
        w.Open($"public {partial}class {model.ClassName} : DatabaseWrapper");

        w.Line($"public {model.ClassName}() : base(\"{Escape(model.ConnectionName)}\") {{ }}");
        w.Blank();
        w.Line($"public {model.ClassName}(DbConnection connection) : base(connection) {{ }}");

        foreach (WrapperEntry entry in model.Entries
                     .OrderBy(e => e.PropertyName, StringComparer.Ordinal))
        {
            w.Blank();
            w.Line($"public DataClassAdapter<{entry.EntityClassName}> {entry.PropertyName} " +
                   $"=> Adapter<{entry.EntityClassName}>();");
        }

        w.Close();
        return w.ToString();
    }

    /// <summary>
    /// Escapes a value that will be interpolated into a regular (non-verbatim) C# string
    /// literal. The connection name is user-supplied config, not a compiler-controlled
    /// identifier, so it can legally contain a double quote or backslash; every such value
    /// reaching a string literal must be routed through here or the emitted source fails to
    /// compile (or worse, changes meaning). Duplicated from CSharpEntityEmitter rather than
    /// shared because that emitter keeps its helper private — promoting it to internal would
    /// mean editing a file this task must leave untouched, for one two-line method.
    /// </summary>
    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
