using System.Text;

namespace Zonkey.Scaffold.Emit;

/// <summary>
/// The VB.NET entity emitter — the same shape as <see cref="CSharpEntityEmitter"/>, in VB syntax.
/// </summary>
/// <remarks>
/// VB has no <c>field</c> keyword, so properties always declare an explicit backing field; the
/// <c>Emit:FieldKeyword</c> option is simply not reachable here. It also has no nullable reference
/// types, so <c>Emit:NullableRefs</c> only affects value types. Named attribute arguments use
/// <c>:=</c>.
/// </remarks>
public sealed class VbEntityEmitter
{
    /// <summary>VB's comment syntax, so the marker differs from the C# emitter's.</summary>
    public const string AutoGeneratedHeader = "' <auto-generated>";

    public string Emit(EntityModel model, EntityEmitOptions options)
    {
        var w = new IndentedWriter();

        w.Line(AutoGeneratedHeader);
        w.Line("'     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("'     Add your own members in a separate partial class file.");
        w.Line("' </auto-generated>");
        w.Blank();

        w.Line("Imports System");
        if (model.Relations.Any(r => r.IsCollection))
            w.Line("Imports System.Collections.Generic");
        w.Line("Imports System.Data");
        w.Line("Imports Zonkey.ObjectModel");
        w.Blank();

        string? ns = model.Namespace ?? options.Namespace;
        bool hasNamespace = !string.IsNullOrWhiteSpace(ns);

        if (hasNamespace)
        {
            w.Push($"Namespace {ns}");
            w.Blank();
        }

        w.Line(DataItemAttribute(model));
        w.Push(ClassDeclaration(model, options));

        if (!model.IsReadOnly)
        {
            w.Line("Inherits DataClass");
            w.Blank();
        }

        if (options.PrivateFieldsAtTop && !model.IsReadOnly)
        {
            foreach (PropertyModel p in model.Properties)
                w.Line($"Private {BackingField(p)} As {VbTypeNames.Translate(p.ClrType)}");

            w.Blank();
        }

        if (!model.IsReadOnly) EmitConstructors(w, model);

        EmitProperties(w, model, options);
        EmitRelations(w, model);

        w.Pop("End Class");

        if (hasNamespace)
        {
            w.Blank();
            w.Pop("End Namespace");
        }

        return w.ToString();
    }

    private static string ClassDeclaration(EntityModel model, EntityEmitOptions options)
        => options.PartialClasses
            ? $"Partial Public Class {model.ClassName}"
            : $"Public Class {model.ClassName}";

    private static void EmitConstructors(IndentedWriter w, EntityModel model)
    {
        w.Push("Public Sub New(ByVal addingNew As Boolean)");
        w.Line("MyBase.New(addingNew)");
        w.Pop("End Sub");
        w.Blank();

        // Same contract as the C# emitter: the materializer constructs through emitted IL and never
        // sees the attribute, while application code calling it gets a compile error.
        w.Line($"<Obsolete(\"Required by the DataClassAdapter materializer; " +
               $"use {Escape(model.ClassName)}(addingNew As Boolean) in code.\", True)>");
        w.Push("Public Sub New()");
        w.Line("MyClass.New(False)");
        w.Pop("End Sub");
        w.Blank();
    }

    private static void EmitProperties(IndentedWriter w, EntityModel model, EntityEmitOptions options)
    {
        for (int i = 0; i < model.Properties.Count; i++)
        {
            PropertyModel p = model.Properties[i];
            string type = VbTypeNames.Translate(p.ClrType);

            w.Line(DataFieldAttribute(p));

            if (model.IsReadOnly)
            {
                w.Line($"Public Property {p.Name} As {type}");
            }
            else
            {
                string backing = BackingField(p);
                string overridable = options.VirtualProperties ? "Overridable " : "";

                w.Push($"Public {overridable}Property {p.Name} As {type}");
                w.Push("Get");
                w.Line($"Return {backing}");
                w.Pop("End Get");
                w.Push($"Set(value As {type})");

                // CallerMemberName supplies the property name, exactly as in C#.
                w.Line($"SetFieldValue({backing}, value)");
                w.Pop("End Set");
                w.Pop("End Property");

                if (!options.PrivateFieldsAtTop)
                    w.Line($"Private {backing} As {type}");
            }

            if (i < model.Properties.Count - 1) w.Blank();
        }
    }

    private static void EmitRelations(IndentedWriter w, EntityModel model)
    {
        if (model.Relations.Count == 0) return;

        w.Blank();
        w.Line("' Related data. These have no <DataField>, so the adapter never reads or writes");
        w.Line("' them - nothing is loaded until you fill them yourself. See");
        w.Line("' docs/modeling-relationships.md.");

        foreach (RelationModel r in model.Relations)
        {
            w.Line($"' {r.Origin}");

            if (r.IsCollection)
                w.Line($"Public ReadOnly Property {r.MemberName} As New List(Of {r.TypeName})");
            else
                w.Line($"Public Property {r.MemberName} As {r.TypeName}");
        }
    }

    private static string DataItemAttribute(EntityModel model)
    {
        var sb = new StringBuilder($"<DataItem(\"{Escape(model.TableName)}\"");

        if (!string.IsNullOrEmpty(model.SchemaName))
            sb.Append($", SchemaName:=\"{Escape(model.SchemaName)}\"");

        if (!string.IsNullOrEmpty(model.SaveToTable))
            sb.Append($", SaveToTable:=\"{Escape(model.SaveToTable)}\"");

        return sb.Append(")>").ToString();
    }

    private static string DataFieldAttribute(PropertyModel p)
    {
        var sb = new StringBuilder(
            $"<DataField(\"{Escape(p.ColumnName)}\", DbType.{p.DbType}, {(p.IsNullable ? "True" : "False")}");

        if (p.Length is > 0 && CSharpEntityEmitter.IsSized(p.DbType))
            sb.Append($", Length:={p.Length}");

        if (p.IsKey) sb.Append(", IsKeyField:=True");
        if (p.IsIdentity) sb.Append(", IsAutoIncrement:=True");
        if (p.IsRowVersion) sb.Append(", IsRowVersion:=True");

        if (!string.IsNullOrEmpty(p.SequenceName))
            sb.Append($", SequenceName:=\"{Escape(p.SequenceName)}\"");

        if (!string.IsNullOrEmpty(p.DateTimeKind))
            sb.Append($", DateTimeKind:=DateTimeKind.{p.DateTimeKind}");

        return sb.Append(")>").ToString();
    }

    /// <summary>VB escapes a quote by doubling it; there are no backslash escapes.</summary>
    private static string Escape(string value) => value.Replace("\"", "\"\"");

    private static string BackingField(PropertyModel p)
        => "m_" + p.Name.TrimStart('@');
}
