namespace Zonkey.Scaffold.Emit;

/// <summary>The VB.NET counterpart of <see cref="CSharpWrapperEmitter"/>.</summary>
public sealed class VbWrapperEmitter
{
    public string Emit(WrapperModel model)
    {
        var w = new IndentedWriter();

        w.Line("' <auto-generated>");
        w.Line("'     This file was generated by zonkey-scaffold. Changes will be overwritten.");
        w.Line("'     Add your own members in a separate partial class file.");
        w.Line("' </auto-generated>");
        w.Blank();

        w.Line("Imports System.Data.Common");
        w.Line("Imports Zonkey");
        w.Line("Imports Zonkey.ObjectModel");
        w.Blank();

        bool hasNamespace = !string.IsNullOrWhiteSpace(model.Namespace);

        if (hasNamespace)
        {
            w.Push($"Namespace {model.Namespace}");
            w.Blank();
        }

        w.Push(model.PartialClasses
            ? $"Partial Public Class {model.ClassName}"
            : $"Public Class {model.ClassName}");

        w.Line("Inherits DatabaseWrapper");
        w.Blank();

        w.Push("Public Sub New()");
        w.Line($"MyBase.New(\"{model.ConnectionName.Replace("\"", "\"\"")}\")");
        w.Pop("End Sub");
        w.Blank();

        w.Push("Public Sub New(connection As DbConnection)");
        w.Line("MyBase.New(connection)");
        w.Pop("End Sub");

        foreach (WrapperEntry entry in model.Entries)
        {
            w.Blank();
            w.Push($"Public ReadOnly Property {entry.PropertyName} As DataClassAdapter(Of {entry.EntityClassName})");
            w.Push("Get");
            w.Line($"Return Adapter(Of {entry.EntityClassName})()");
            w.Pop("End Get");
            w.Pop("End Property");
        }

        w.Pop("End Class");

        if (hasNamespace)
        {
            w.Blank();
            w.Pop("End Namespace");
        }

        return w.ToString();
    }
}
