using Xunit;
using Zonkey.Scaffold.Diagnostics;
using Zonkey.Scaffold.Io;

public class GeneratedFileWriterTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("zwriter").FullName;
    public void Dispose() => Directory.Delete(_dir, recursive: true);

    private string Path_(string name) => Path.Combine(_dir, name);

    private const string Generated =
        "// <auto-generated>\n//     zonkey-scaffold\n// </auto-generated>\n\nclass X { }\n";

    [Fact]
    public void Creates_a_new_file()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        Assert.Equal(WriteOutcome.Created, w.Write(Path_("A.g.cs"), Generated));
        Assert.Equal(Generated, File.ReadAllText(Path_("A.g.cs")));
    }

    [Fact]
    public void Creates_missing_directories()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        string nested = Path.Combine(_dir, "Data", "Entities", "A.g.cs");
        w.Write(nested, Generated);
        Assert.True(File.Exists(nested));
    }

    [Fact]
    public void Overwrites_a_file_that_carries_the_header()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("A.g.cs"), Generated);

        string updated = Generated.Replace("class X", "class Y");
        Assert.Equal(WriteOutcome.Overwritten, w.Write(Path_("A.g.cs"), updated));
        Assert.Contains("class Y", File.ReadAllText(Path_("A.g.cs")));
    }

    [Fact]
    public void Reports_unchanged_when_content_is_identical()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("A.g.cs"), Generated);
        Assert.Equal(WriteOutcome.Unchanged, w.Write(Path_("A.g.cs"), Generated));
    }

    // ---- one path, one write, per run ------------------------------------------------
    //
    // Defence in depth behind the name-level collision check. Two emitters targeting the same
    // path in a single run is always a bug — the second write destroys the first file's contents
    // and both files legitimately carry the header, so the overwrite guard permits it and the
    // only trace is a "Created" then "Overwritten" pair in the report that reads as normal. This
    // catches it generically, including for emitters that do not exist yet.

    [Fact]
    public void Refuses_to_write_the_same_path_twice_in_one_run()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        Assert.Equal(WriteOutcome.Created, w.Write(Path_("A.g.cs"), Generated));

        var ex = Assert.Throws<ScaffoldException>(
            () => w.Write(Path_("A.g.cs"), Generated.Replace("class X", "class Y")));

        Assert.Contains("A.g.cs", ex.Message);
        // The first write's content must survive: the refusal happens before the second write.
        Assert.Contains("class X", File.ReadAllText(Path_("A.g.cs")));
    }

    [Fact]
    public void Same_path_twice_is_refused_in_dry_run_too()
    {
        var w = new GeneratedFileWriter(dryRun: true);
        w.Write(Path_("A.g.cs"), Generated);

        Assert.Throws<ScaffoldException>(() => w.Write(Path_("A.g.cs"), Generated));
    }

    /// <summary>
    /// A second run is a normal regeneration, not a collision — the tracking is per writer
    /// instance, and GenerateCommand creates one writer per invocation.
    /// </summary>
    [Fact]
    public void A_fresh_writer_may_rewrite_the_same_path()
    {
        new GeneratedFileWriter(dryRun: false).Write(Path_("A.g.cs"), Generated);
        Assert.Equal(WriteOutcome.Unchanged,
            new GeneratedFileWriter(dryRun: false).Write(Path_("A.g.cs"), Generated));
    }

    [Fact]
    public void Different_paths_in_one_run_are_fine()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        Assert.Equal(WriteOutcome.Created, w.Write(Path_("A.g.cs"), Generated));
        Assert.Equal(WriteOutcome.Created, w.Write(Path_("B.g.cs"), Generated));
    }

    [Fact]
    public void Refuses_to_overwrite_a_file_without_the_header()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("A.g.cs"), "// hand written, do not delete\nclass X { }\n");

        var ex = Assert.Throws<ScaffoldException>(() => w.Write(Path_("A.g.cs"), Generated));

        Assert.Contains("A.g.cs", ex.Message);
        Assert.Contains("hand-written", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Refused_file_is_left_completely_untouched()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        const string original = "// hand written\nclass X { }\n";
        File.WriteAllText(Path_("A.g.cs"), original);

        Assert.Throws<ScaffoldException>(() => w.Write(Path_("A.g.cs"), Generated));
        Assert.Equal(original, File.ReadAllText(Path_("A.g.cs")));
    }

    [Fact]
    public void Guard_keys_on_the_header_not_the_filename()
    {
        // Dropping the .g suffix must not drop the guardrail — that would be exactly backwards,
        // since a plain name is what makes generated files look hand-written.
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("Plain.cs"), "class Handwritten { }\n");

        Assert.Throws<ScaffoldException>(() => w.Write(Path_("Plain.cs"), Generated));
    }

    [Fact]
    public void Header_is_recognised_after_a_utf8_bom()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("A.g.cs"), Generated, new System.Text.UTF8Encoding(true));
        Assert.Equal(WriteOutcome.Overwritten, w.Write(Path_("A.g.cs"), Generated.Replace("X", "Y")));
    }

    [Fact]
    public void Dry_run_reports_but_writes_nothing()
    {
        var w = new GeneratedFileWriter(dryRun: true);
        Assert.Equal(WriteOutcome.Created, w.Write(Path_("A.g.cs"), Generated));
        Assert.False(File.Exists(Path_("A.g.cs")));
    }

    [Fact]
    public void Dry_run_still_enforces_the_guard()
    {
        var w = new GeneratedFileWriter(dryRun: true);
        File.WriteAllText(Path_("A.g.cs"), "class Handwritten { }\n");
        Assert.Throws<ScaffoldException>(() => w.Write(Path_("A.g.cs"), Generated));
    }

    [Fact]
    public void Writes_without_a_bom_and_with_lf_endings()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        w.Write(Path_("A.g.cs"), Generated);

        byte[] bytes = File.ReadAllBytes(Path_("A.g.cs"));
        Assert.False(bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF);
        Assert.DoesNotContain((byte)'\r', bytes);
    }

    [Fact]
    public void IsGenerated_detects_the_header()
    {
        File.WriteAllText(Path_("A.g.cs"), Generated);
        File.WriteAllText(Path_("B.cs"), "class B { }");

        Assert.True(GeneratedFileWriter.IsGenerated(Path_("A.g.cs")));
        Assert.False(GeneratedFileWriter.IsGenerated(Path_("B.cs")));
        Assert.False(GeneratedFileWriter.IsGenerated(Path_("missing.cs")));
    }

    // --- Red-team fix-up: the marker must be anchored to the start of the file, not merely
    // present somewhere in the probe window. A hand-written file that quotes or documents the
    // marker text near its top must never be classified as generated.

    [Fact]
    public void Marker_present_but_not_at_the_start_is_not_treated_as_generated()
    {
        var w = new GeneratedFileWriter(dryRun: false);

        // Realistic case: a source file that *declares* the marker constant, the way
        // CSharpEntityEmitter.cs itself does. The literal text appears well within the first
        // 256 characters, but the file does not start with it.
        const string original =
            "using System.Text;\n\n" +
            "namespace Example;\n\n" +
            "public sealed class Marker\n" +
            "{\n" +
            "    public const string AutoGeneratedHeader = \"// <auto-generated>\";\n" +
            "}\n";
        File.WriteAllText(Path_("A.g.cs"), original);

        var ex = Assert.Throws<ScaffoldException>(() => w.Write(Path_("A.g.cs"), Generated));
        Assert.Contains("A.g.cs", ex.Message);

        Assert.Equal(original, File.ReadAllText(Path_("A.g.cs")));
        Assert.False(GeneratedFileWriter.IsGenerated(Path_("A.g.cs")));
    }

    [Fact]
    public void Generated_file_with_marker_as_first_line_is_still_accepted()
    {
        // Guard against over-correcting: anchoring to the start must not stop recognising the
        // ordinary case where the header genuinely is the first line.
        File.WriteAllText(Path_("A.g.cs"), Generated);
        Assert.True(GeneratedFileWriter.IsGenerated(Path_("A.g.cs")));

        var w = new GeneratedFileWriter(dryRun: false);
        string updated = Generated.Replace("class X", "class Z");
        Assert.Equal(WriteOutcome.Overwritten, w.Write(Path_("A.g.cs"), updated));
    }

    [Fact]
    public void Stale_bom_on_an_otherwise_identical_generated_file_is_overwritten_and_removed()
    {
        // Unchanged must be a byte comparison, not a text comparison: a file that decodes to the
        // same text but still carries a stale UTF-8 BOM is byte-different and must be rewritten
        // so the BOM is actually removed, matching the class's own no-BOM contract.
        var w = new GeneratedFileWriter(dryRun: false);
        File.WriteAllText(Path_("A.g.cs"), Generated, new System.Text.UTF8Encoding(true));

        Assert.Equal(WriteOutcome.Overwritten, w.Write(Path_("A.g.cs"), Generated));

        byte[] bytes = File.ReadAllBytes(Path_("A.g.cs"));
        Assert.False(bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF);
        Assert.Equal(Generated, File.ReadAllText(Path_("A.g.cs")));
    }

    [Fact]
    public void Directory_path_throws_ScaffoldException_naming_the_path()
    {
        var w = new GeneratedFileWriter(dryRun: false);
        string dirPath = Path.Combine(_dir, "SubDir");
        Directory.CreateDirectory(dirPath);

        var ex = Assert.Throws<ScaffoldException>(() => w.Write(dirPath, Generated));
        Assert.Contains(dirPath, ex.Message);
    }

    [Fact]
    public void Real_source_file_declaring_the_marker_constant_is_not_misclassified()
    {
        // The exact scenario the red-team review reproduced: CSharpEntityEmitter.cs declares
        // `AutoGeneratedHeader = "// <auto-generated>"` near the top of the file, which a
        // Contains-based probe misreads as the file itself being generated. This must return
        // false, or the tool would overwrite its own source.
        string path = RepoRootRelative(Path.Combine("tools", "Zonkey.Scaffold", "Emit", "CSharpEntityEmitter.cs"));
        Assert.True(File.Exists(path));
        Assert.False(GeneratedFileWriter.IsGenerated(path));
    }

    private static string RepoRootRelative(string relativePath)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null && !File.Exists(Path.Combine(dir.FullName, "Zonkey.sln")))
            dir = dir.Parent;

        if (dir == null)
            throw new InvalidOperationException(
                "Could not locate repository root (Zonkey.sln) above " + AppContext.BaseDirectory);

        return Path.Combine(dir.FullName, relativePath);
    }
}
