<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0;net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Zonkey</RootNamespace>
		<PackageTags>orm;database;data-access;ado-net;sql-server;postgresql;mysql;sqlite;oracle;db2</PackageTags>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Zonkey ORM</Title>
		<Authors>Kelly Birr</Authors>
		<Company />
		<Description>Zonkey ORM Library</Description>
		<PackageProjectUrl>https://github.com/kellybirr/zonkey</PackageProjectUrl>
		<RepositoryUrl>https://github.com/kellybirr/zonkey</RepositoryUrl>
		<IncludeSymbols>False</IncludeSymbols>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
		<Reference Include="System.Configuration" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
	</ItemGroup>

</Project>
