using Xunit;
using Zonkey.Scaffold.Diagnostics;
using Zonkey.Scaffold.Emit;

public class CSharpEntityEmitterTests
{
    private static EntityModel Order() => new()
    {
        ClassName = "Order",
        TableName = "orders",
        Properties =
        [
            new PropertyModel { Name = "Id", ColumnName = "id", DbType = "Int32",
                                ClrType = "int", IsKey = true, IsIdentity = true },
            new PropertyModel { Name = "Name", ColumnName = "name", DbType = "String",
                                ClrType = "string", Length = 100 },
            new PropertyModel { Name = "Notes", ColumnName = "notes", DbType = "String",
                                ClrType = "string?", IsNullable = true, Length = 500 },
        ]
    };

    private static EntityEmitOptions Opts(bool fieldKeyword = true) => new()
    {
        Namespace = "MyApp.Data",
        PartialClasses = true,
        VirtualProperties = false,
        FieldKeyword = fieldKeyword,
        NullableRefs = true
    };

    private static string Emit(EntityModel? m = null, EntityEmitOptions? o = null)
        => new CSharpEntityEmitter().Emit(m ?? Order(), o ?? Opts());

    [Fact]
    public void Starts_with_the_auto_generated_header()
        => Assert.StartsWith("// <auto-generated>", Emit());

    [Fact]
    public void Header_carries_no_timestamp_or_version()
    {
        string code = Emit();
        Assert.DoesNotContain("2026", code);
        Assert.DoesNotContain("7.0.0", code);
    }

    [Fact]
    public void Emits_namespace_and_data_item_attribute()
    {
        string code = Emit();
        Assert.Contains("namespace MyApp.Data", code);
        Assert.Contains("[DataItem(\"orders\")]", code);
    }

    [Fact]
    public void Emits_schema_name_when_present()
    {
        var m = Order();
        m.SchemaName = "store";
        Assert.Contains("[DataItem(\"orders\", SchemaName = \"store\")]", Emit(m));
    }

    [Fact]
    public void Emits_partial_class_deriving_DataClass()
        => Assert.Contains("public partial class Order : DataClass", Emit());

    [Fact]
    public void Non_partial_when_disabled()
    {
        var o = Opts();
        o.PartialClasses = false;
        Assert.Contains("public class Order : DataClass", Emit(null, o));
    }

    [Fact]
    public void Emits_obsolete_parameterless_constructor()
    {
        string code = Emit();
        Assert.Contains("public Order(bool addingNew) : base(addingNew)", code);
        Assert.Contains("[Obsolete(", code);
        Assert.Contains("public Order() : this(false) { }", code);
    }

    [Fact]
    public void Obsolete_attribute_is_error_level()
        => Assert.Matches(@"\[Obsolete\("".*"", true\)\]", Emit());

    [Fact]
    public void Field_keyword_mode_emits_no_backing_fields()
    {
        string code = Emit(null, Opts(fieldKeyword: true));
        Assert.Contains("public int Id { get => field; set => SetFieldValue(ref field, value); }", code);
        Assert.DoesNotContain("private int _id;", code);
    }

    [Fact]
    public void Backing_field_mode_emits_private_fields()
    {
        string code = Emit(null, Opts(fieldKeyword: false));
        Assert.Contains("private int _id;", code);
        Assert.Contains("get => _id;", code);
        Assert.Contains("set => SetFieldValue(ref _id, value);", code);
    }

    [Fact]
    public void PrivateFieldsAtTop_groups_fields_before_properties()
    {
        var o = Opts(fieldKeyword: false);
        o.PrivateFieldsAtTop = true;
        string code = Emit(null, o);

        int firstField = code.IndexOf("private int _id;", StringComparison.Ordinal);
        int firstProperty = code.IndexOf("public int Id", StringComparison.Ordinal);
        Assert.True(firstField < firstProperty);
    }

    [Fact]
    public void Emits_key_and_identity_flags()
        => Assert.Contains(
            "[DataField(\"id\", DbType.Int32, false, IsKeyField = true, IsAutoIncrement = true)]",
            Emit());

    [Fact]
    public void Emits_length_for_strings()
        => Assert.Contains("Length = 100", Emit());

    // Regression coverage for the SQL Server NTEXT/TEXT/IMAGE length bug: SqlServerSchemaReader
    // must report MaxLength = null for those three legacy LOB types (see
    // SqlServerSchemaReaderTests.Legacy_lob_types_report_null_length_not_their_pointer_stub_size),
    // and ScaffoldPipeline.cs:304 copies ColumnInfo.MaxLength straight into PropertyModel.Length
    // with no further logic -- so a null here is the one property this emitter needs to get right
    // for the whole chain to actually omit a bogus size from the generated [DataField]. Before the
    // reader fix, an NTEXT column's MaxLength (and therefore Length here) came out as 8 -- the
    // in-row LOB pointer's 16-byte stub halved by the Unicode-length correction -- which this test
    // would have caught as "Length = 8" appearing below.
    [Fact]
    public void Omits_length_entirely_when_null()
    {
        var m = Order();
        m.Properties.Add(new PropertyModel { Name = "Description", ColumnName = "description",
                                              DbType = "String", ClrType = "string?",
                                              IsNullable = true, Length = null });

        string code = Emit(m);
        // The exact-string assertion (attribute closes right after the nullability flag) is the
        // real proof: if Length were emitted for a null value, this line simply would not match.
        Assert.Contains("[DataField(\"description\", DbType.String, true)]", code);
    }

    [Fact]
    public void Emits_nullability_as_the_third_positional_argument()
    {
        string code = Emit();
        Assert.Contains("[DataField(\"notes\", DbType.String, true", code);
        Assert.Contains("[DataField(\"name\", DbType.String, false", code);
    }

    [Fact]
    public void Virtual_properties_when_enabled()
    {
        var o = Opts();
        o.VirtualProperties = true;
        Assert.Contains("public virtual int Id", Emit(null, o));
    }

    [Fact]
    public void Readonly_model_omits_DataClass_base_and_constructors()
    {
        var m = Order();
        m.IsReadOnly = true;
        string code = Emit(m);

        Assert.Contains("public partial class Order", code);
        Assert.DoesNotContain(": DataClass", code);
        Assert.DoesNotContain("SetFieldValue", code);
        Assert.DoesNotContain("[Obsolete(", code);
        Assert.Contains("public int Id { get; set; }", code);
    }

    [Fact]
    public void SaveToTable_is_emitted_when_set()
    {
        var m = Order();
        m.SaveToTable = "orders_base";
        Assert.Contains("SaveToTable = \"orders_base\"", Emit(m));
    }

    [Fact]
    public void Output_is_byte_identical_across_runs()
        => Assert.Equal(Emit(), Emit());

    [Fact]
    public void Uses_lf_line_endings_only()
        => Assert.DoesNotContain("\r", Emit());

    [Fact]
    public void Nullable_directive_emitted_when_NullableRefs_enabled()
    {
        var o = Opts();
        o.NullableRefs = true;
        Assert.Contains("#nullable enable", Emit(null, o));
    }

    [Fact]
    public void Nullable_directive_omitted_when_NullableRefs_disabled()
    {
        var o = Opts();
        o.NullableRefs = false;
        Assert.DoesNotContain("#nullable enable", Emit(null, o));
    }

    // ---- CS8618/CS9264: non-nullable storage the constructor never assigns ----------
    //
    // Under "#nullable enable" a non-nullable reference-typed backing field that no constructor
    // writes is a compiler warning (an error in any project with TreatWarningsAsErrors), which
    // made the tool's normal output dirty-to-broken in every modern consumer project. The value
    // really is supplied out of band by the materializer, so "= null!" states the truth; the fix
    // must stay narrow, which is what the negative cases below pin.

    [Fact]
    public void Non_nullable_reference_backing_field_is_null_forgiving()
        => Assert.Contains("private string _name = null!;", Emit(null, Opts(fieldKeyword: false)));

    [Fact]
    public void Nullable_reference_backing_field_is_not_null_forgiving()
    {
        string code = Emit(null, Opts(fieldKeyword: false));
        Assert.Contains("private string? _notes;", code);
        Assert.DoesNotContain("private string? _notes = null!;", code);
    }

    [Fact]
    public void Value_typed_backing_field_is_not_null_forgiving()
    {
        string code = Emit(null, Opts(fieldKeyword: false));
        Assert.Contains("private int _id;", code);
        Assert.DoesNotContain("_id = null!", code);
    }

    [Fact]
    public void Nothing_is_null_forgiving_when_nullable_refs_are_off()
    {
        var o = Opts(fieldKeyword: false);
        o.NullableRefs = false;
        Assert.DoesNotContain("null!", Emit(null, o));
    }

    [Fact]
    public void Field_keyword_property_carries_the_null_forgiving_initializer()
    {
        string code = Emit(null, Opts(fieldKeyword: true));
        Assert.Contains(
            "public string Name { get => field; set => SetFieldValue(ref field, value); } = null!;", code);
        Assert.Contains(
            "public string? Notes { get => field; set => SetFieldValue(ref field, value); }\n", code);
    }

    [Fact]
    public void PrivateFieldsAtTop_block_is_null_forgiving_too()
    {
        var o = Opts(fieldKeyword: false);
        o.PrivateFieldsAtTop = true;
        Assert.Contains("private string _name = null!;", Emit(null, o));
    }

    [Fact]
    public void Readonly_auto_property_is_null_forgiving()
    {
        var m = Order();
        m.IsReadOnly = true;
        string code = Emit(m);

        Assert.Contains("public string Name { get; set; } = null!;", code);
        Assert.Contains("public int Id { get; set; }\n", code);
    }

    [Fact]
    public void Column_name_with_embedded_quote_is_escaped()
    {
        var m = Order();
        m.Properties[0].ColumnName = "i\"d";
        string code = Emit(m);
        Assert.Contains("[DataField(\"i\\\"d\", DbType.Int32, false", code);
    }

    [Fact]
    public void Table_name_with_embedded_quote_is_escaped()
    {
        var m = Order();
        m.TableName = "ord\"ers";
        string code = Emit(m);
        Assert.Contains("[DataItem(\"ord\\\"ers\")]", code);
    }

    [Fact]
    public void Class_name_with_embedded_quote_is_escaped_in_obsolete_message()
    {
        var m = Order();
        m.ClassName = "Ord\"er";
        string code = Emit(m);
        Assert.Contains("use Ord\\\"er(bool addingNew) in code.", code);
    }

    // ---- CS9258: a property named `field` under --field-keyword ----------------------
    //
    // `field` is a legal identifier and so is deliberately not escaped by NamingEngine. But
    // inside a property accessor it binds to the synthesized backing field, so a member named
    // `field` makes every `get => field;` in the whole class ambiguous — the diagnostic is
    // class-wide, which is why the fallback has to be too.

    private static EntityModel WithFieldColumn()
    {
        var m = Order();
        m.Properties.Add(new PropertyModel
        {
            Name = "field", ColumnName = "field", DbType = "String", ClrType = "string"
        });
        return m;
    }

    [Fact]
    public void A_property_named_field_disables_field_keyword_mode_for_the_whole_class()
    {
        string code = Emit(WithFieldColumn(), Opts(fieldKeyword: true));

        Assert.DoesNotContain("get => field;", code);
        Assert.Contains("private string _field = null!;", code);
        // Every sibling drops to a backing field too: leaving them on `field` is what raises
        // CS9258 on properties that have nothing to do with the offending column.
        Assert.Contains("private int _id;", code);
        Assert.Contains("get => _name;", code);
    }

    [Fact]
    public void An_escaped_property_named_field_disables_it_too()
    {
        var m = WithFieldColumn();
        m.Properties[^1].Name = "@field";

        Assert.DoesNotContain("get => field;", Emit(m, Opts(fieldKeyword: true)));
    }

    [Fact]
    public void A_class_without_such_a_column_still_uses_the_field_keyword()
        => Assert.Contains("get => field;", Emit(Order(), Opts(fieldKeyword: true)));

    [Fact]
    public void PrivateFieldsAtTop_is_honoured_by_the_field_fallback()
    {
        var o = Opts(fieldKeyword: true);
        o.PrivateFieldsAtTop = true;
        string code = Emit(WithFieldColumn(), o);

        int firstField = code.IndexOf("private int _id;", StringComparison.Ordinal);
        int firstProperty = code.IndexOf("public int Id", StringComparison.Ordinal);
        Assert.True(firstField >= 0 && firstField < firstProperty);
    }

    /// <summary>
    /// Every option must survive the fallback's copy of <see cref="EntityEmitOptions"/>.
    /// </summary>
    /// <remarks>
    /// Driven by reflection rather than by a list of property names, deliberately: the failure this
    /// guards against is a property added to <c>EntityEmitOptions</c> later and not added to the
    /// copy, which would be dropped <em>only</em> for classes that contain a <c>field</c> column —
    /// one file out of a run, no golden baseline moved, nothing to notice. A hand-written list of
    /// today's properties would be exactly as easy to forget to extend as the copy was.
    /// </remarks>
    [Fact]
    public void The_field_keyword_fallback_carries_every_option_through()
    {
        EntityModel model = WithFieldColumn();

        string Render(Action<EntityEmitOptions> mutate)
        {
            var o = new EntityEmitOptions { Namespace = "MyApp.Data", FieldKeyword = true };
            mutate(o);
            return new CSharpEntityEmitter().Emit(model, o);
        }

        string baseline = Render(_ => { });
        var covered = new List<string>();

        foreach (var p in typeof(EntityEmitOptions).GetProperties()
                     .Where(p => p.CanWrite && p.PropertyType == typeof(bool))
                     .Where(p => p.Name != nameof(EntityEmitOptions.FieldKeyword)))
        {
            string flipped = Render(o => p.SetValue(o, !(bool)p.GetValue(o)!));

            Assert.True(flipped != baseline,
                $"EntityEmitOptions.{p.Name} has no effect once the `field` fallback has copied " +
                "the options — it was dropped by the copy.");

            covered.Add(p.Name);
        }

        // The one non-bool property, checked explicitly so the loop above cannot be the whole test.
        Assert.Contains("namespace Other.Ns;", Render(o => o.Namespace = "Other.Ns"));

        // If EntityEmitOptions ever loses all its booleans the loop would pass vacuously.
        Assert.NotEmpty(covered);
    }

    // ---- CS8981: an all-lower-case class name ---------------------------------------
    //
    // --naming-style preserve against a lower_snake_case schema names the class after the table,
    // so an ordinary table yields a type name made only of lower-case ASCII. That is a warning
    // the caller cannot act on without renaming their tables, and an error under
    // TreatWarningsAsErrors, so the generated file states that it accepts the risk.

    [Fact]
    public void All_lower_case_class_name_suppresses_CS8981()
    {
        var m = Order();
        m.ClassName = "orders";
        Assert.Contains("#pragma warning disable CS8981", Emit(m));
    }

    [Theory]
    [InlineData("Order")]        // has an upper-case letter
    [InlineData("order_line")]   // underscore: not all lower-case ASCII
    [InlineData("order2")]       // digit: not all lower-case ASCII
    [InlineData("@event")]       // verbatim identifiers are exempt from CS8981
    public void Class_names_the_diagnostic_does_not_apply_to_carry_no_pragma(string className)
    {
        var m = Order();
        m.ClassName = className;
        Assert.DoesNotContain("#pragma", Emit(m));
    }

    // ---- identifiers that are not identifiers ---------------------------------------

    [Fact]
    public void A_property_name_that_is_only_an_escape_is_refused_not_crashed()
    {
        var m = Order();
        m.Properties[0].Name = "@";

        // Must be a ScaffoldException naming the column (exit 1, "refused"), never an
        // IndexOutOfRangeException from deriving the backing field name (exit 2, "crashed").
        var ex = Assert.Throws<ScaffoldException>(() => Emit(m, Opts(fieldKeyword: false)));
        Assert.Contains("id", ex.Message);
    }
}
