using Xunit;
using Zonkey.Scaffold.Emit;

public class CSharpWrapperEmitterTests
{
    private static WrapperModel Model() => new()
    {
        ClassName = "ZooDatabase",
        ConnectionName = "Zoo",
        Namespace = "MyApp.Data",
        PartialClasses = true,
        Entries =
        [
            new WrapperEntry { PropertyName = "Animals", EntityClassName = "Animal" },
            new WrapperEntry { PropertyName = "Species", EntityClassName = "Species" },
        ]
    };

    private static string Emit(WrapperModel? m = null)
        => new CSharpWrapperEmitter().Emit(m ?? Model());

    [Fact]
    public void Starts_with_the_auto_generated_header()
        => Assert.StartsWith("// <auto-generated>", Emit());

    [Fact]
    public void Derives_from_DatabaseWrapper()
        => Assert.Contains("public partial class ZooDatabase : DatabaseWrapper", Emit());

    [Fact]
    public void Emits_connection_name_constructor()
        => Assert.Contains("public ZooDatabase() : base(\"Zoo\") { }", Emit());

    [Fact]
    public void Emits_connection_object_constructor()
        => Assert.Contains("public ZooDatabase(DbConnection connection) : base(connection) { }", Emit());

    [Fact]
    public void Emits_one_typed_adapter_property_per_entity()
    {
        string code = Emit();
        Assert.Contains("public DataClassAdapter<Animal> Animals => Adapter<Animal>();", code);
        Assert.Contains("public DataClassAdapter<Species> Species => Adapter<Species>();", code);
    }

    [Fact]
    public void Includes_required_usings()
    {
        string code = Emit();
        Assert.Contains("using System.Data.Common;", code);
        // DataClassAdapter<T> lives in the "Zonkey" namespace, not "Zonkey.ObjectModel" — it
        // only resolves without a using inside library files because they sit in the nested
        // Zonkey.ObjectModel namespace. Generated code lives in the consumer's own namespace,
        // so both usings are required or the property declarations fail to compile (CS0246).
        Assert.Contains("using Zonkey;", code);
        Assert.Contains("using Zonkey.ObjectModel;", code);
    }

    [Fact]
    public void Property_named_same_as_type_still_compiles_via_explicit_qualification()
    {
        // "Species" is both the entity type and the property name; the generic argument
        // must still bind to the type, so the property is emitted with the type first.
        Assert.Contains("public DataClassAdapter<Species> Species", Emit());
    }

    [Fact]
    public void Output_is_byte_identical_across_runs()
        => Assert.Equal(Emit(), Emit());

    [Fact]
    public void Uses_lf_line_endings_only()
        => Assert.DoesNotContain("\r", Emit());

    [Fact]
    public void Escapes_connection_name_reaching_the_string_literal()
    {
        var model = Model();
        model.ConnectionName = "Zoo\"; // injected";
        string code = Emit(model);
        Assert.Contains("base(\"Zoo\\\"; // injected\")", code);
    }

    [Fact]
    public void Entries_are_emitted_in_Ordinal_sorted_order_not_input_order()
    {
        // Entries are supplied deliberately out of order. A Contains check on each property
        // would pass even if sorting were removed entirely, so this asserts relative position
        // in the emitted string instead.
        var model = Model();
        model.Entries =
        [
            new WrapperEntry { PropertyName = "Zookeepers", EntityClassName = "Zookeeper" },
            new WrapperEntry { PropertyName = "Animals", EntityClassName = "Animal" },
            new WrapperEntry { PropertyName = "Species", EntityClassName = "Species" },
        ];

        string code = Emit(model);
        int animals = code.IndexOf("public DataClassAdapter<Animal> Animals =>", StringComparison.Ordinal);
        int species = code.IndexOf("public DataClassAdapter<Species> Species =>", StringComparison.Ordinal);
        int zookeepers = code.IndexOf("public DataClassAdapter<Zookeeper> Zookeepers =>", StringComparison.Ordinal);

        Assert.True(animals >= 0 && species >= 0 && zookeepers >= 0, "all three properties must be present");
        Assert.True(animals < species, "Animals (A) must precede Species (S)");
        Assert.True(species < zookeepers, "Species (S) must precede Zookeepers (Z)");
    }

    /// <summary>
    /// The wrapper declares a type just as the entity emitter does, so an all-lower-case
    /// <c>--wrapper-class</c> raises the same CS8981 and needs the same suppression. Fixing only
    /// the entity emitter would leave the identical break one file away.
    /// </summary>
    [Fact]
    public void All_lower_case_wrapper_class_name_suppresses_CS8981()
    {
        var model = Model();
        model.ClassName = "zoodatabase";
        Assert.Contains("#pragma warning disable CS8981", Emit(model));
    }

    [Fact]
    public void A_normal_wrapper_class_name_carries_no_pragma()
        => Assert.DoesNotContain("#pragma", Emit());

    [Fact]
    public void Uses_ordinal_comparison_not_culture_aware_sorting()
    {
        // Under StringComparer.Ordinal, uppercase 'B' (0x42) sorts before lowercase 'a' (0x61),
        // so "Banana" precedes "apple". Under StringComparer.InvariantCulture the linguistic
        // base-letter comparison ignores case first, so "apple" would precede "Banana" instead.
        // If the emitter's comparer were ever swapped to a culture-aware one, this assertion
        // flips and fails — pinning the *choice* of Ordinal, not just that sorting happens.
        var model = Model();
        model.Entries =
        [
            new WrapperEntry { PropertyName = "apple", EntityClassName = "Apple" },
            new WrapperEntry { PropertyName = "Banana", EntityClassName = "Banana" },
        ];

        string code = Emit(model);
        int banana = code.IndexOf("public DataClassAdapter<Banana> Banana =>", StringComparison.Ordinal);
        int apple = code.IndexOf("public DataClassAdapter<Apple> apple =>", StringComparison.Ordinal);

        Assert.True(banana >= 0 && apple >= 0, "both properties must be present");
        Assert.True(banana < apple, "Ordinal comparison must place 'Banana' before 'apple'");
    }
}
