using System.Text;
using Zonkey.Scaffold.Diagnostics;
using Zonkey.Scaffold.Emit;

namespace Zonkey.Scaffold.Io;

public enum WriteOutcome { Created, Overwritten, Unchanged }

/// <summary>
/// The most important guardrail in the tool. Generated files are overwritten wholesale — never
/// merged — which is only safe because a file that does not carry the &lt;auto-generated&gt;
/// header is never touched. An agent regenerating a schema must not be able to eat code a
/// person wrote.
/// </summary>
public sealed class GeneratedFileWriter(bool dryRun)
{
    /// <summary>How many leading characters to scan for the marker.</summary>
    private const int HeaderProbeLength = 256;

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    /// <summary>
    /// Every path this writer has already been handed. One instance is created per `generate`
    /// invocation, so this is per-run state.
    /// </summary>
    /// <remarks>
    /// The name-level checks upstream (entity vs. entity, entity vs. wrapper) are the real fix
    /// for the cases known today; this is the generic net beneath them, and it costs a hash set.
    /// Writing the same path twice in one run is always a defect — the second write destroys what
    /// the first produced, both files carry the &lt;auto-generated&gt; marker so the overwrite
    /// guard correctly permits it, and the only evidence is a Created/Overwritten pair in the file
    /// report that reads like an ordinary regeneration. Any emitter added later gets this for
    /// free.
    /// <para>
    /// Compared case-insensitively: on Windows and macOS two paths differing only in case are the
    /// same file, so treating them as distinct would let exactly this bug through on the platforms
    /// most users are on. On a case-sensitive filesystem the cost is refusing a pair of outputs
    /// that differ only in case — which could not be checked out on the other two platforms
    /// anyway.
    /// </para>
    /// </remarks>
    private readonly HashSet<string> _claimed = new(StringComparer.OrdinalIgnoreCase);

    public WriteOutcome Write(string path, string content)
    {
        if (!_claimed.Add(Path.GetFullPath(path)))
            throw new ScaffoldException(
                $"Two generated files resolve to the same path '{path}' in a single run; the " +
                "second would destroy the first. This is a naming collision that slipped past " +
                "the class-name check — rename one with overrides.tables.<table>.className, " +
                "--wrapper-class, or separate the outputs with --wrapper-out.");

        if (Directory.Exists(path))
            throw new ScaffoldException(
                $"Cannot write '{path}': a directory already exists at that path. " +
                "Point --out somewhere else, or remove the directory first.");

        if (File.Exists(path))
        {
            if (!IsGenerated(path))
                throw new ScaffoldException(
                    $"Refusing to overwrite '{path}': the file exists but does not carry the " +
                    $"'{CSharpEntityEmitter.AutoGeneratedHeader}' marker, so it looks hand-written. " +
                    "Move or delete it, or point --out somewhere else.");

            // Byte comparison, not text comparison: a file that decodes to the same text but
            // still carries a stale BOM (or different line endings) is not actually identical to
            // what this writer would produce, and must be rewritten so drift doesn't linger.
            byte[] existingBytes = ReadAllBytesSafe(path);
            byte[] newBytes = Utf8NoBom.GetBytes(content);
            if (existingBytes.AsSpan().SequenceEqual(newBytes)) return WriteOutcome.Unchanged;

            if (!dryRun) WriteFile(path, content);
            return WriteOutcome.Overwritten;
        }

        if (!dryRun) WriteFile(path, content);
        return WriteOutcome.Created;
    }

    public static bool IsGenerated(string path)
    {
        if (!File.Exists(path)) return false;

        try
        {
            using var reader = new StreamReader(path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);

            char[] buffer = new char[HeaderProbeLength];
            int read = reader.Read(buffer, 0, buffer.Length);

            // Anchored to the start of the file, not merely "somewhere in the probe window".
            // A hand-written file that quotes or documents the marker text near its top — a
            // comment, a doc string, a const declaration like the one in CSharpEntityEmitter.cs
            // itself — must never be mistaken for a generated file. The marker is always the
            // literal first line of anything this tool emits, so nothing but leading whitespace
            // may precede it. There is deliberately no Contains fallback: a fallback reopens the
            // exact hole this anchor closes. StreamReader with BOM detection already strips the
            // BOM before any character reaches this buffer, so a BOM'd file still starts, from
            // this method's point of view, with the marker text itself.
            ReadOnlySpan<char> probe = buffer.AsSpan(0, read).TrimStart();
            return probe.StartsWith(CSharpEntityEmitter.AutoGeneratedHeader, StringComparison.Ordinal);
        }
        catch (IOException)
        {
            // Unreadable means "cannot prove it is generated", which must fail closed.
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static void WriteFile(string path, string content)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);

        try
        {
            File.WriteAllText(path, content, Utf8NoBom);
        }
        catch (UnauthorizedAccessException ex)
        {
            throw new ScaffoldException(
                $"Cannot write '{path}': access was denied. Check that the path is not a " +
                "directory and that you have permission to write there, then try again.", ex);
        }
    }

    private static byte[] ReadAllBytesSafe(string path)
    {
        try { return File.ReadAllBytes(path); }
        catch (IOException) { return []; }
        catch (UnauthorizedAccessException) { return []; }
    }
}
