<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0;net48</TargetFrameworks>
    <PackageTags>orm;database;data-access;sql-server;mssql;bulk-insert</PackageTags>
    <RootNamespace>Zonkey</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Zonkey MS-SQL Extension</Title>
    <Authors>Kelly Birr</Authors>
    <Description>MS-SQL Extensions for Zonkey.Data</Description>
    <PackageProjectUrl>https://github.com/kellybirr/zonkey</PackageProjectUrl>
    <RepositoryUrl>https://github.com/kellybirr/zonkey</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net48'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zonkey.Data\Zonkey.Data.csproj" />
  </ItemGroup>

</Project>
